(() => {
//i'm like 99% sure this works :D
function normalizePunctuation(text) {
if (!text) return text;
return text
.replace(/\s*,\s*\./g, ".")
.replace(/\s*\.\s*,/g, ".")
.replace(/([.,!?])\1+/g, "$1")
.replace(/\s+([.,!?])/g, "$1")
.replace(/([.,!?])([A-Za-z])/g, "$1 $2")
.replace(/([.!?]\s+)([a-z])/g, (_, p1, p2) => p1 + p2.toUpperCase())
.replace(/^\s*([a-z])/g, m => m.toUpperCase())
.trim();
}
function xmur3(str) {
let h = 1779033703 ^ str.length;
for (let i = 0; i < str.length; i++) {
h = Math.imul(h ^ str.charCodeAt(i), 3432918353);
h = (h << 13) | (h >>> 19);
}
return function () {
h = Math.imul(h ^ (h >>> 16), 2246822507);
h = Math.imul(h ^ (h >>> 13), 3266489909);
h ^= h >>> 16;
return h >>> 0;
};
}
function mulberry32(seed) {
return function () {
let t = (seed += 0x6D2B79F5);
t = Math.imul(t ^ (t >>> 15), t | 1);
t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};
}
function randInt(rng, maxExclusive) {
return Math.floor(rng() * maxExclusive);
}
function pick(rng, arr) {
const v = arr[randInt(rng, arr.length)];
return (v === undefined || v === null) ? "" : String(v);
}
function isoDayLocal() {
const d = new Date();
const y = d.getFullYear();
const m = String(d.getMonth() + 1).padStart(2, "0");
const day = String(d.getDate()).padStart(2, "0");
return `${y}-${m}-${day}`;
}
function getOrCreateUserId() {
let user = localStorage.getItem("username");
if (user && user.trim()) return user.trim();
user = localStorage.getItem("user_id");
if (user && user.trim()) return user.trim();
const id = "u_" + Math.random().toString(16).slice(2) + Date.now().toString(16);
localStorage.setItem("user_id", id);
return id;
}
function makeDailyRng(userId) {
const day = isoDayLocal();
const ua = navigator.userAgent || "";
const seedStr = `${userId}|${day}|${ua}`;
const seed = xmur3(seedStr)();
return mulberry32(seed);
}
function ordinalSuffix(n) {
const mod100 = n % 100;
if (mod100 >= 11 && mod100 <= 13) return "th";
switch (n % 10) {
case 1: return "st";
case 2: return "nd";
case 3: return "rd";
default: return "th";
}
}
function capFirst(s) {
if (!s) return s;
return s.charAt(0).toUpperCase() + s.slice(1);
}
function generatePrescript(rng) {
const locationA = [
"海滩",
"商店",
"房子",
"公寓大楼",
"海洋",
"酒店",
"汽车旅馆",
"你珍视的地方",
"你安置家人的地方",
"餐厅",
"吃饭的地方",
"剧院",
"图书馆",
"学校",
"工厂",
"后街小巷",
"巢穴",
"空旷的田野",
"墓地",
"地下室",
"小巷",
"停车场",
"废弃的空地",
"办公室",
"工作室",
"没人会检查两次的地方",
"人们匆匆经过的地方",
"不会永远存在的地方",
"闻起来像灰尘的地方",
"有回声的地方",
"你被告知不能进入的地方",
"公共厕所",
"火车站台",
"灯塔",
"只有你知道的秘密地点",
"你称之为家的地方",
"他们称之为家的地方",
"你会藏匿尸体的地方"
];
const finalllocation = pick(rng, locationA);

const preprescript = [
"今天下午1点，在11区的街道上，将一个午餐盒放在垃圾桶顶上并吃掉它。",
"在时针指向7点到8点之间时烤制达克瓦兹蛋糕，并在看电影时吃掉它。",
"与最先遇到的五个人玩 我从来没有 游戏。当有人弯曲一根手指时，就折断它。",
"整齐地剪掉你遇到的第六十二个人的指甲。",
"抚摸四足动物五次。",
"抚摸四足动物五次。",
"旋转转盘，将蛋糕扔向结果所指的人。",
"同时吃掉八只在室温下储存的螃蟹和成熟的柿子。",
"在建筑物屋顶的栏杆旁，喊出你讨厌的人的名字，然后跳下去。建筑物的高度无关紧要。",
"饭后，丢弃所有用来盛放饭菜的餐具。",
"收到指令后的第二天早上，一醒来就喝三杯水。",
"与住在同一栋楼的居民比赛前往7区。每23分钟测量一次距离，淘汰离目的地最远的人。",
"三天内，织一条有蝴蝶图案的围巾。",
"拨打任意号码。向接电话的人送上新年祝福和祝福的话语。",
"从白墙上看到绿色。",
"蠕虫。老鼠。昆虫。其余的你会知道。",
"饥饿时，吃一个加了洋葱的Cheeki's芝士汉堡。",
"折三十九只纸鹤，然后从屋顶扔下去。",
"在工作中，割掉第一个对你发怒的人的耳朵。",
"当你的目光与另一个人相遇时，向他们点头。",
"立即回家。只有当一只狗在你家门前叫一次后，你才能离开。",
"穿着浅绿色衣服，在三角形的小巷里走10步。",
"称呼你遇到的第一个人为同性恋，然后吻他们。",
"在读完e的值之前不要回家。",
"在40万米处，向右转。",
"每天总共睡800小时。",
"只用右手吃饭和写字。",
"在网上订购一些你不需要的东西。",
"服从城市的指令。",
"把钱浪费在某人身上。",
"去睡觉。你必须梦到一只关在笼子里的鸟。鸟的颜色无关紧要。",
"确保2加2等于5。",
"访问索引并领取你的个性化奖励。",
"重走你今天走过的所有路线。一旦回到床上，触摸自己。",
"重复昨天的指令。你必须确保戴着眼镜。",
"明天回来，把你的指令执行两次。",
"服从今天你收到的第一个命令。",
"购买一件你永远不会用的东西",
"在"+finalllocation+ "找到一个人，并确保他们再也无法说话。",
"在"+finalllocation+ "找到一个人，并倾听他们说的话。",
"去一个"+finalllocation,
"去一个"+finalllocation,
"去一个不熟悉的地方，静静观察10分钟。",
"当你看到一个电视头家伙时，订阅他们的Patreon。这条指令100%不是伪造的。",
]

// made these more rare.
const israndom = randInt(rng, 150);

if (israndom === 4) {
return pick(
rng,
preprescript
);
}

const personidentifyer = [
"丑陋的",
"美丽的",
"英俊的",
"可爱的",
"漂亮的",
"普通的",
"吸引人的",
"不吸引人的",
"性感的",
"年轻的",
"年老的",
"中年的",
"老年的",
"充满青春活力的",
"年迈的",
"高的",
"矮的",
"小的",
"大的",
"瘦的",
"胖的",
"皮包骨的",
"圆润的",
"精瘦的",
"肌肉发达的",
"虚弱的",
"强壮的",
"衰弱的",
"苍白的",
"黝黑的",
"晒成古铜色的",
"带伤疤的",
"有雀斑的",
"布满皱纹的",
"光滑的",
"金发的",
"深色头发的",
"黑发的",
"红发的",
"秃头的",
"灰白头发",
"善良的",
"刻薄的",
"自私的",
"慷慨的",
"温柔的",
"残酷的",
"友好的",
"敌对的",
"冷漠的",
"热情的",
"睿智的",
"愚蠢的",
"聪明的",
"笨的",
"机灵的",
"天真的",
"自信的",
"害羞的",
"笨拙的",
"有魅力的",
"紧张的",
"冷静的",
"攻击性强的",
"被动的",
"健康的",
"多病的",
"疲惫的",
"精力充沛的",
"死气沉沉的",
"善良的",
"刻薄的",
"自私的",
"慷慨的",
"温柔的",
"残酷的",
"友好的",
"敌对的",
"冷漠的",
"热情的",
"自信的",
"缺乏安全感的",
"害羞的",
"大胆的",
"笨拙的",
"有魅力的",
"安静的",
"吵闹的",
"内敛的",
"外向的",
"冷静的",
"焦虑的",
"紧张的",
"放松的",
"紧绷的",
"攻击性强的",
"被动的",
"果断的",
"聪明的",
"机灵的",
"睿智的",
"愚蠢的",
"天真的",
"好奇的",
"善于观察的",
"心不在焉的",
"诚实的",
"不诚实的",
"值得信赖的",
"不可靠的",
"忠诚的",
"背信弃义的",
"乐观的",
"悲观的",
"充满希望的",
"愤世嫉俗的",
"有同理心的",
"有同情心的",
"漠不关心的",
"有同情心的",
"耐心的",
"不耐烦的",
"冲动的",
"鲁莽的",
"谨慎的",
"有条理的",
"有创造力的",
"富有想象力的",
"务实的",
"逻辑性强的",
"情绪化的",
"超然的",
"有抱负的",
"懒惰的",
"有动力的",
"缺乏动力的",
"保护欲强的",
"控制欲强的",
"顺从的",
"支配的",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",

];
const finalpersonidentifyer = pick(rng, personidentifyer);

const personidentifyer2 = [
"最丑陋的",
"最漂亮的",
"最英俊的",
"最可爱的",
"最令人毛骨悚然的",
"最善良的",
"最好的",
"最刻薄的",
"最残酷的",
"最友好的",
"最冷漠的",
"最热情的",
"最聪明的",
"最笨的",
"最睿智的",
"最丑陋的",
"最漂亮的",
"最英俊的",
"最可爱的",
"最令人毛骨悚然的",
"最善良的",
"最好的",
"最刻薄的",
"最残酷的",
"最友好的",
"最冷漠的",
"最热情的",
"最聪明的",
"最笨的",
"最睿智的",
"最机灵的",
"最天真的",
"最强壮的",
"最虚弱的",
"最强硬的",
"最衰弱的",
"最勇敢的",
"最大胆的",
"最害羞的",
"最安静的",
"最吵闹的",
"最搞笑的",
"最古怪的",
"最书呆子气的",
"最傻气的",
"最笨拙的",
"最慷慨的",
"最自私的",
"最忠诚的",
"最值得信赖的",
"最欺骗性的",
"最自信的",
"最缺乏安全感的",
"最焦虑的",
"最冷静的",
"最有创造力的",
"最富有想象力的",
"最逻辑的",
"最情绪化的",
"最不稳定的",
"最精神错乱的",
"最疯狂的",
"最反复无常的",
"最混乱的",
"最偏执的",
"最妄想症的",
"最强迫性的",
"最执着的",
"最狂躁的",
"最暴力的",
"最具攻击性的",
"最虐待狂的",
"最无情的",
"最冷酷的",
"最具掠夺性的",
"最善于操控的",
"最具欺骗性的",
"控制欲最强的",
"最精于算计的",
"最自恋的",
"最自我中心的",
"最自我陶醉的",
"最冷血的",
"最无情的",
"最冷酷无情的",
"最可怕的",
"最令人生畏的",
"最威胁性的",
"最阴险的",
"最不可阻挡的",
"最不懈的",
"最具支配力的",
"心如黑曜石般的",
"最榨取灵魂的",
"最噩梦般的",
"最孤立的",
"最疏离的",
"最无感情的",
"最不可预测的",
"最反复无常的",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",

];
const finalpersonidentifyer2 = pick(rng, personidentifyer2);

const color1 = [
"蓝色 ",
"黑色 ",
"红色 ",
"棕色 ",
"天鹅绒色 ",
"黄色 ",
"粉色 ",
"白色 ",
"灰色 ",
"绿色 ",
"浅绿色 ",
"浅红色 ",
"深红色 ",
"深绿色 ",
"青色 ",
"蓝绿色 ",
"紫色 ",
"紫罗兰色 ",
"品红色 ",
"橙色 ",
"琥珀色 ",
"金色 ",
"银色 ",
"米色 ",
"棕褐色 ",
"象牙色 ",
"奶油色 ",
"炭灰色 ",
"栗色 ",
"海军蓝 ",
"靛蓝色 ",
"深红色 ",
"猩红色 ",
"酸橙色 ",
"薄荷色 ",
"橄榄色 ",
"桃色 ",
"薰衣草色 ",
"梅子色 ",
"锈色 ",
"铜色 ",
"青铜色 ",
"钢青色 ",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
];

const finalcolor1 = pick(rng, color1);
const finalcolorrequire = pick(rng, color1);

const persontype = [
"朋友",
"最好的朋友",
"孩子",
"青少年",
"朋友",
"最好的朋友",
"成年人",
"老人",
"陌生人",
"邻居",
"访客",
"你遇到的人",
"路人",
"成年人",
"老人",
"陌生人",
"邻居",
"访客",
"路人",
"家庭成员",
"兄弟姐妹",
"父母",
"亲戚",
"老师",
"学生",
"牧师",
"修女",
"僧侣",
"拇指成员",
"中指成员",
"食指成员",
"小指成员",
"无名指成员",
"一只老鼠",
"一只老鼠",
"高阶收尾人",
"低阶收尾人",
"高阶收尾人",
"低阶收尾人",
"协会成员",
"无名小卒",
"官员",
"领导者",
"医生",
"护士",
"看护人",
"屠夫",
"面包师",
"商人",
"守卫",
"收尾人",
"村民",
"本地人",
"外来者",
"外国人",
"旅行者",
"流浪者",
"漂泊者",
"顾客",
"客户",
"主人",
"客人",
"受害者",
"幸存者",
"目击者",
"后巷里的某人",
"色彩收尾人",
"追随者",
"信徒",
"你街区里的知名人物",
"不知名的人",
"无家可归的男人",
"醉汉",
"无家可归的女人",
"醉酒的女人",
"邻居",
"你遇到的人",
"陌生人",
"陌生人",
"陌生人",
"人",
"人",
"人",
"陌生人",
"陌生人",
"陌生人",
"人",
"人",
"人",
"人",
"人",
];

const finalptype = pick(rng, persontype);

const persontype2 = [
"朋友",
"陌生人",
"家人",
"熟人",
"熟悉的人",
"未知的人",
"亲近的人",
"疏远的人",
"熟悉的东西",
"亲近的东西",
"疏远的东西",
"人",
"人们",
"人物",
"活物",
"移动的东西",
"注视的东西",
"呼吸的东西",
"类人的东西",
"类动物的东西",
"两足生物",
"四足生物",
"多足生物",
"没有腿的东西",
"两条腿的东西",
"四条腿的东西",
"很多腿的东西",
"存在",
"剪影",
"形状",
"人类",
"人形生物",
"非人类",
"动物",
"四足动物",
"生物",
"有机体",
"活物",
"实体",
"存在物",
"生命形式",
"观察者",
"目击者",
"参与者",
"个体",
"集体",
"活物",
"注视的东西",
"移动的东西",
"陌生人",
"陌生人",
"陌生人",
"人",
"人",
"人",
"陌生人",
"陌生人",
"陌生人",
"人",
"人",
"人",
"人",
"未知的东西",
"已知的东西",
"未识别的东西",
];
const finalptype1 = pick(rng, persontype);
const finalptype2 = pick(rng, persontype2);
const finalptype3 = pick(rng, persontype2);

const isperson = randInt(rng, 2);

const number1 = randInt(rng, 150) + 1;
const number7 = randInt(rng, 100) + 1;
const number2 = randInt(rng, 400) + 1;
const number4 = randInt(rng, 1300) + 1;
const number5 = randInt(rng, 6) + 1;
const number9 = randInt(rng, 8) + 1;
const number8 = randInt(rng, 7) + 1;
const number11 = randInt(rng, 12) + 1;

const end1 = ordinalSuffix(number1);
const end7 = ordinalSuffix(number7);
const end8 = ordinalSuffix(number8);

const clothing = [
"帽子",
"无边便帽",
"兜帽",
"连帽衫",
"斗篷",
"外套",
"夹克",
"马甲",
"衬衫",
"T恤",
"运动衫",
"毛衣",
"女士上衣",
"连衣裙",
"裙子",
"长袍",
"裤子",
"长裤",
"牛仔裤",
"短裤",
"打底裤",
"袜子",
"长袜",
"连裤袜",
"鞋子",
"靴子",
"凉鞋",
"拖鞋",
"手套",
"连指手套",
"围巾",
"披肩",
"腰带",
"背带",
"面具",
"面罩",
"面纱",
"眼镜",
"护目镜",
"眼罩",
"丝带",
"发夹",
"头带",
"制服",
"服装",
];
const material_condition = [
"布 ",
"织物 ",
"皮革 ",
"牛仔 ",
"羊毛 ",
"棉 ",
"亚麻 ",
"丝绸 ",
"天鹅绒 ",
"毛皮 ",
"橡胶 ",
"塑料 ",
"金属 ",
"钢 ",
"铁 ",
"黄铜 ",
"光滑的 ",
"粗糙的 ",
"粗糙的 ",
"柔软的 ",
"硬挺的 ",
"滑溜的 ",
"粘性的 ",
"新的 ",
"旧的 ",
"磨损的 ",
"破烂的 ",
"磨损的 ",
"打补丁的 ",
"磨薄的 ",
"破裂的 ",
"褪色的 ",
"撕裂的 ",
"撕破的 ",
"撕碎的 ",
"坏掉的 ",
"弯曲的 ",
"干净的 ",
"脏的 ",
"污秽的 ",
"布满灰尘的 ",
"沾满泥的 ",
"油腻的 ",
"有污渍的 ",
"湿的 ",
"潮湿的 ",
"湿透的 ",
"干的 ",
"发霉的 ",
"腐烂的 ",
"沾血的 ",
"浸油的 ",
"覆灰的 ",
"烧焦的 ",
"炭化的 ",
"重的 ",
"轻的 ",
"宽松的 ",
"紧身的 ",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
];

const finalclothing = pick(rng, material_condition) + pick(rng, clothing);
const finalclothing2 = pick(rng, material_condition) + pick(rng, clothing);

const games = [
"拍手游戏",
"我从来没有过",
"真心话大冒险",
"捉人游戏",
"捉迷藏",
"躲猫猫",
"跳房子",
"西蒙说",
"红灯绿灯",
"冰冻捉人",
"马可波罗",
"国际象棋",
"跳棋",
"双陆棋",
"多米诺骨牌",
"扭扭乐",
"哑剧猜词",
"你宁愿",
"彩弹球",
"石头剪刀布",
"井字游戏",
"一个曾被警告过的游戏",
"一个被告知永远不要玩的游戏",
"一个规则不断变化的游戏",
"一个没人解释的游戏",
"一个大家都假装不记得的游戏",
"一个由成年人玩的儿童游戏",
"一个只给孩子玩的游戏",
"一个午夜后玩的游戏",
"一个在沉默中玩的游戏",
"一个没人笑的游戏",
"一个总会有人离开的游戏",
"一个会跟着你回家的游戏",
"一个不会结束的游戏",
"一个你会不断失去时间感的游戏",
"一个有失踪玩家的游戏",
"一个多出一个参与者的游戏",
"一个不请自来的游戏",
"一个你独自玩的游戏",
"一个反过来玩你的游戏",
"一个知道你的名字的游戏",
"一个在黑暗中玩的游戏",
"一个对着镜子玩的游戏",
"一个在没人看时玩的游戏",
"一个你不记得同意过的游戏",
"一个你无法停止的游戏",
];
const finalgames = pick(rng, games);

// props only
const objcs = [
finalclothing,
finalclothing2,
"笔和纸",
"铅笔",
"橡皮擦",
"苹果",
"空瓶子",
"玻璃杯",
"陶瓷杯",
finalcolor1 + "有 " + number1 + " 页的笔记本",
finalcolor1 + "文件夹",
finalcolor1 + "信封",
"有 " + number5 + " 片叶子的植物",
"枯死的植物",
"盆栽植物",
"一袋土",
"胶带",
"一卷胶带",
"细绳",
"绳索",
"木炭",
"粉笔",
"灰烬",
"塑料制品",
"塑料容器",
"塑料袋",
"木椅",
pick(rng, clothing),
pick(rng, clothing),
pick(rng, material_condition) + pick(rng, clothing),
pick(rng, material_condition) + pick(rng, clothing),
"破凳子",
"一副扑克牌",
"一张扑克牌",
"骰子",
"勺子",
"叉子",
"刀子",
"空盘子",
"蜡笔",
"颜料",
"画笔",
"卫生纸",
"纸巾",
"纸巾",
"旧照片",
"一张" + pick(rng, persontype) + "的照片",
"一具" + pick(rng, persontype) + "的尸体",
"某个" + pick(rng, persontype) + "的重要物品",
"某个" + pick(rng, persontype) + "的遗物",
"带框的图片",
"缺了某人的照片",
"钥匙",
"有 " + number1 + " 把钥匙的钥匙圈",
"锁着的盒子",
"背包",
"纸袋",
"纸板箱",
"手电筒",
"没电的手电筒",
"电池",
"时钟",
"坏掉的钟",
"手表",
"镜子",
"有裂缝的镜子",
"小镜子",
"重物",
"尖锐物",
"温暖的东西",
"冰冷的东西",
"日历",
"墙上海报",
"钱包",
"零钱",
"没有锁的钥匙",
"没有钥匙的锁",
"挂锁",
"密码锁",
"鞋盒",
"工具箱",
"急救箱",
"雨伞",
"雨衣",
"毯子",
"枕头",
"床单",
"台灯",
"桌灯",
"灯泡",
"延长线",
"电源排插",
"手机充电器",
"遥控器",
"旧手机",
"没电的手机",
"收音机",
"充满杂音的收音机",
"电视机",
"无信号的屏幕",
"相机",
"一次性相机",
"存储卡",
"写了一半的笔记本",
"撕掉页的笔记本",
"密封的信封",
"拆开的信封",
"写字板",
"文件活页夹",
"垃圾袋",
"空盒子",
"密封的盒子",
"地图",
"折叠的地图",
"缺页的地图",
"闹钟",
"计时器",
"卷尺",
"尺子",
"扫帚",
"簸箕",
"水桶",
"空桶",
"肥皂条",
"肥皂瓶",
"毛巾",
"湿毛巾",
"门把手",
"松动的铰链",
"窗玻璃",
"碎玻璃片",
"姓名牌",
"身份证",
"遗物",
"锤子",
"木槌",
"螺丝刀",
"扳手",
"钳子",
"手锯",
"美工刀",
"油漆桶",
"滚筒托盘",
"油漆滚筒",
"梯子",
"踏步凳",
"独轮车",
"铲子",
"铁锹",
"耙子",
"锄头",
"喷水壶",
"花园软管",
"洒水器",
"花盆",
"空花盆",
"砖块",
"煤渣砖",
"一堆石头",
"胶合板",
"防护布",
"链条",
"金属桶",
"工作手套",
"安全帽",
"手电筒",
"灯笼",
"汽油罐",
"油罐",
"燃料容器",
"空容器",
"冷却器",
"冰袋",
"露营炉",
"丙烷罐",
"帐篷桩",
"睡袋",
"背包框架",
"钓鱼竿",
"网",
"板条箱",
"交通锥",
"警告标志",
"轮胎",
"E.G.O",
"武器",
"工坊武器",
"松散的皮带",
];
const finalobjcs = pick(rng, objcs);

const topic = [
"爱",
"生命",
"死亡",
"恐惧",
"后悔",
"希望",
"孤独",
"信任",
"愧疚",
"欲望",
"你的秘密",
"你的欲望",
"你的恐惧",
"你的过去",
"你的未来",
"你自己",
"记忆",
"被遗忘的记忆",
"虚假的记忆",
"梦境",
"反复出现的梦",
"噩梦",
"生活",
"游戏",
"城市",
"一部电影",
"你遇到的第" + number1 + end1 + "个人",
"你暗恋的人",
"你最喜欢的食物",
"你的秘密",
"你的欲望",
"你自己",
"天气",
"事态",
"初音未来",
"梦想",
"twitter.com上的最新帖子",
"外星生命",
"twitter.com上的第" + number1 + end1 + "条帖子",
"reddit上的第" + number1 + end1 + "条帖子",
"鸟",
"烟",
"加密货币",
"毒品",
"你最喜欢的" + finalclothing,
"钱",
"你的未来",
"你的性取向",
"石头",
"糖果",
"镜子",
"现实",
"宗教",
"科学",
"怀疑",
"自由意志",
"信仰",
"数学",
"欲望",
"科技",
"翼",
"你几乎记得的事情",
"从未发生过的事情",
"时间",
"失去时间感",
"一个" + finalptype1,
"一个" + finalptype2,
"你曾经认识的人",
"你刚遇见的人",
"认识你的人",
"正在注视的人",
"不应该在这里的人",
"你遇到的第" + number1 + end1 + "个人",
"你后悔的一次对话",
"你没有遵守的诺言",
"你目睹的一次争吵",
"一个无法撤销的选择",
"一个改变一切的错误",
"你玩过一次的游戏",
"玩 " + finalgames,
"在 " + finalgames + " 中输掉",
"在 " + finalgames + " 中获胜",
"你丢失的一件物品",
"你找到的一件物品",
"不属于这里的东西",
"你埋藏的东西",
"你隐藏的东西",
"远处注视的东西",
"近处注视的东西",
"城市",
"这个地方",
"熟悉的地方",
"陌生的地方",
"家",
"汽车旅馆",
"没有窗户的房间",
"你不该回去的地方",
"身份",
"意义",
"目的",
"规则",
"打破规则",
"接下来会发生什么",
"如果你离开会发生什么",
"如果你留下会发生什么",
"食物",
"咖啡",
"快餐",
"天气",
"鸟",
"烟",
"火",
"水",
"游戏",
"一部电影",
"科技",
"数学",
"权力",
"权威",
"正义",
"惩罚",
"原谅",
"同意",
"隐私",
"界限",
"家庭",
"友谊",
"亲密",
"孤独",
"嫉妒",
"痴迷",
"暴力",
"和平",
"冲突",
"顺从",
"抵抗",
"学生",
"走路",
"打扫",
"扫地",
"清洗",
"烹饪",
"烘焙",
"吃",
"喝",
"休息",
"睡觉",
"阅读",
"写作",
"学习",
"计数",
"园艺",
"耕作",
"修理",
"建造",
"测量",
"学徒",
"常态",
"越轨",
"禁忌",
"接纳",
"政治",
"互联网",
"感觉不对劲的事情",
"你不该注意到的事情",
"大家都回避谈论的事情",
"跟随你的事情",
"等待的事情",
"初音未来",
"为什么人们穿" + pick(rng, color1) + "色的衣服",
"已不存在的协会",
"没人记得起源的传统",
"拇指",
"食指",
"中指",
"小指",
"无名指",
"收尾人",
"色彩收尾人",
"一个协会",
"你假装成的人",
"你真实的样子",
"你想成为的人",
"人们对你的假设",
"你如何介绍自己",
"你回应过的名字",
"你经过的地方",
"你逗留的地方",
"和一个" + finalptype1 + "交谈",
"避开一个" + finalptype1,
"误判一个" + finalptype1,
"被误认为是一个" + finalptype1,
"数字 " + number1 + " 的意义",
"为什么第" + number1 + end1 + "次感觉不一样",
"计数那些不需要计数的事物",
"为什么 " + pick(rng, color1) + " 在这里感觉不一样",
"颜色象征意义",
"与警告相关的颜色",
"为什么有些问题感觉危险",
"遇到一个" + finalptype2,
"注意到一个" + finalptype2,
"被一个" + finalptype2 + "跟踪",
"想象一个" + finalptype2,
"你避开的地方",
"夜晚会变化的地方",
"感觉被注视的地方",
"感觉空荡的地方",
"血魔",
];
const finaltopic = pick(rng, topic);

// It just occurred to me, I don't actually HAVE To like, store these...
// now that i have rng pick i can just, pick. Lol. so I will do that for a few of these...
// thank GOODNESS nobody is looking at this code... right? O_O
const activities = [
"犯下重罪",
"偷钱",
"背叛朋友",
"成为代理",
"玩" + finalgames,
"谈论" + finaltopic,
"和你握手",
"喝点什么",
"坐在铁轨上",
"去新的地方旅行",
"从水坑里喝水",
"吃点新东西",
"做后空翻",
"做前空翻",
"绕城市跑一圈",
"和你交换钱包",
"掷骰子",
"挥棒球棒",
"为一个" + finalptype3 + "做个蛋糕",
"送一份指令",
"看部电影",
"目睹一场死亡",
"出去吃晚餐",
"爬进垃圾桶",
"从桥上跳下",
"用蜡笔画画",
"然后点火烧掉它们",
"问关于" + pick(rng, topic) + "的事情",
"向他们求婚",
"检查武器",
"丢弃这份指令",
"给他们做顿好饭",
"拥抱他们然后把他们推下桥",
"开车去" + finalllocation,
"量他们的身高",
"问他们的名字",
"和他们睡觉",
"剪掉你所有的头发",
"遮住你的脸",
"给他们买 " + number9 + " 个" + finalcolorrequire + "物品",
"把你的头发染成" + finalcolorrequire,
"剥开痂然后喝血",
"量他们的身高",
"和你的兄弟姐妹握手",
"对他们的孩子做同样的事",
"把恒温器调到 " + number7 + "°F",
"把食物放在你家门口外",
"把食物放在一个" + finalllocation + "外面",
"带他们去一个" + finalllocation,
"回家",
"忘记这份指令",
"来个 gritty 舞",
"捡起一个" + pick(rng, objcs),
"无缘无故地拿着一个" + pick(rng, objcs) + "到处走",
"把一个" + pick(rng, objcs) + "在地上拖行",
"把一个" + pick(rng, objcs) + "藏在附近某处",
"埋掉一个" + pick(rng, objcs),
"挖出一个" + pick(rng, objcs),
"弄丢一个" + pick(rng, objcs) + "并假装它从未存在过",
"找到一个感觉格格不入的" + pick(rng, objcs),
"仔细检查一个" + pick(rng, objcs),
"擦拭干净一个" + pick(rng, objcs),
"把一个" + pick(rng, objcs) + "清洗到看起来像新的一样",
"故意弄坏一个" + pick(rng, objcs),
"修复一个本不该可修复的" + pick(rng, objcs),
"把一个" + pick(rng, objcs) + "放在地上然后走开",
"把一个" + pick(rng, objcs) + "留在一户人家门口",
"丢下一个" + pick(rng, objcs) + "然后继续走",
"用一个" + pick(rng, objcs) + "交换信息",
"向一个" + finalptype1 + "提供一个" + pick(rng, objcs),
"用一个" + pick(rng, objcs) + "威胁一个" + finalptype1,
"警告一个" + finalptype1 + "关于那个" + pick(rng, objcs),
"让一个" + finalptype1 + "拿着一个" + pick(rng, objcs),
"拿着一个" + pick(rng, objcs) + "跟踪一个" + finalptype1,
"用一个" + pick(rng, objcs) + "制作粗糙的东西",
"试图用一个" + pick(rng, objcs) + "修理东西",
"用一个" + pick(rng, objcs) + "测量东西",
"用一个" + pick(rng, objcs) + "撑开门",
"把一个" + pick(rng, objcs) + "摆得像它本来就在那里",
"把一个" + pick(rng, objcs) + "从一个地方移到另一个地方",
"把一个" + pick(rng, objcs) + "和其他杂物堆在一起",
"把一个" + pick(rng, objcs) + "扔向远处",
"挥动一个" + pick(rng, objcs) + "离某人太近",
"只带着一个" + pick(rng, objcs) + "离开城镇",
"拿着一个" + pick(rng, objcs) + "进入一栋建筑",
"拿着一个" + pick(rng, objcs) + "躲在黑暗中",
"把一个" + pick(rng, objcs) + "摆成一条完美的直线",
"把一个" + pick(rng, objcs) + "摆得像一个警告",
"把一个" + pick(rng, objcs) + "放在路边",
"用一个" + pick(rng, objcs) + "作为信号",
"用一个" + pick(rng, objcs) + "作为分散注意力的东西",
"寻找一个你发誓已经找到过的" + pick(rng, objcs),
"发现一个昨天还不存在的" + pick(rng, objcs),
"给一个" + pick(rng, objcs) + "起个名字",
"和一个" + pick(rng, objcs) + "说话，好像它能听见",
"观星",
"看云",
"观察人群",
"散步",
"询问一个" + finalptype1 + "的名字",
"开车兜风",
"坐在水边",
"看日落",
"看日出",
"喝咖啡",
"吃快餐",
"做晚餐",
"洗碗",
"聊几个小时",
"避开眼神接触",
"小声争吵",
"笑得太大声",
"分享一个秘密",
"撒个小谎",
"撒个大谎",
"进行晚餐约会",
"取消计划",
"不请自来",
"跑到累",
"爬栅栏",
"爬上床",
"睡在地板上",
"躲在哪里",
"打破东西",
"修好坏掉的东西",
"拿重物",
"摔碎易碎品",
"摸狗",
"喂动物",
"跟动物走",
"看动物打架",
"听昆虫叫",
"走进高草丛",
"喝酒",
"喝太多",
"开始打架",
"结束打架",
"去打一个" + finalptype2,
"威胁一个" + finalptype1,
"向一个" + finalptype1 + "道歉",
"和他们玩" + finalgames,
"在" + finalgames + "中输掉",
"在" + finalgames + "中获胜",
"不知为何而等待",
"等待永远不会来的人",
"沉默地站着",
"一动不动地站着",
"听呼吸声",
"数秒",
"失去时间感",
"忘记正在做的事",
"错误地记住某事",
"挖个洞",
"填平洞",
"埋东西",
"寻找丢失的东西",
"藏起重要的东西",
"发现不该发现的东西",
"摸温暖的东西",
"摸冰冷的东西",
"找家汽车旅馆",
"离开城镇",
"进入建筑",
"从另一扇门离开",
"迷路",
"被找到",
"绕远路",
"什么也不做",
"突然停下",
"不告而别",
"把自己伪装成穿着" + pick(rng, color1) + "色衣服的协会成员",
"破坏当地的" + finalptype1,
"什么也不做",
"站着不动",
"突然离开",
"跑到车流中",
"站得离边缘太近",
"爬去不稳定的地方",
"从高处跳下",
"无视明显的危险",
"无缘无故冒险",
"独自去某处",
"和其他人分开",
"把自己锁在里面",
"困住自己",
"躲在没人会找的地方",
"流血",
"受伤",
"无视伤情",
"忍着痛继续",
"倒在陌生的地方",
"意外伤害某人",
"故意伤害某人",
"让某人受伤",
"看着某人受苦而无动于衷",
"做得太过分",
"越过底线",
"做出无法撤销的选择",
"意识到已经太迟",
"向一个被遗忘已久的协会致敬",
"待到早晨",
"模仿你街区里的一个知名人物",
"把别人的牛奶换成另一种类似物质",
];

//I could have totally just like, added a modifier 'ing' thing. dude. okay this is basically unused.
const activitiesfurther = [
"犯下重罪",
"偷钱",
"背叛朋友",
"成为代理",
"玩" + finalgames,
"谈论" + finaltopic,
"和你握手",
"喝点什么",
"坐在铁轨上",
"去新的地方旅行",
"从水坑里喝水",
"吃点新东西",
"做后空翻",
"做前空翻",
"绕城市跑一圈",
"和你交换钱包",
"掷骰子",
"挥棒球棒",
"为一个" + finalptype3 + "做个蛋糕",
"送一份指令",
"看部电影",
"目睹一场死亡",
"出去吃晚餐",
"爬进垃圾桶",
"从桥上跳下",
"用蜡笔画画",
"然后点火烧掉它们",
"问关于" + pick(rng, topic) + "的事情",
"向他们求婚",
"检查武器",
"丢弃这份指令",
"给他们做顿好饭",
"拥抱他们然后把他们推下桥",
"开车去" + finalllocation,
"量他们的身高",
"问他们的名字",
"和他们睡觉",
"剪掉你所有的头发",
"遮住你的脸",
"给他们买 " + number9 + " 个" + finalcolorrequire + "物品",
"把你的头发染成" + finalcolorrequire,
"剥开痂然后喝血",
"量他们的身高",
"和你的兄弟姐妹握手",
"对他们的孩子做同样的事",
"把恒温器调到 " + number7 + "°F",
"把食物放在你家门口外",
"把食物放在一个" + finalllocation + "外面",
"带他们去一个" + finalllocation,
"回家",
"忘记这份指令",
"来个 gritty 舞",
"捡起一个" + pick(rng, objcs),
"无缘无故地拿着一个" + pick(rng, objcs) + "到处走",
"把一个" + pick(rng, objcs) + "在地上拖行",
"把一个" + pick(rng, objcs) + "藏在附近某处",
"埋掉一个" + pick(rng, objcs),
"挖出一个" + pick(rng, objcs),
"弄丢一个" + pick(rng, objcs) + "并假装它从未存在过",
"找到一个感觉格格不入的" + pick(rng, objcs),
"仔细检查一个" + pick(rng, objcs),
"擦拭干净一个" + pick(rng, objcs),
"把一个" + pick(rng, objcs) + "清洗到看起来像新的一样",
"故意弄坏一个" + pick(rng, objcs),
"修复一个本不该可修复的" + pick(rng, objcs),
"把一个" + pick(rng, objcs) + "放在地上然后走开",
"把一个" + pick(rng, objcs) + "留在一户人家门口",
"丢下一个" + pick(rng, objcs) + "然后继续走",
"用一个" + pick(rng, objcs) + "交换信息",
"向一个" + finalptype1 + "提供一个" + pick(rng, objcs),
"用一个" + pick(rng, objcs) + "威胁一个" + finalptype1,
"警告一个" + finalptype1 + "关于那个" + pick(rng, objcs),
"让一个" + finalptype1 + "拿着一个" + pick(rng, objcs),
"拿着一个" + pick(rng, objcs) + "跟踪一个" + finalptype1,
"用一个" + pick(rng, objcs) + "制作粗糙的东西",
"试图用一个" + pick(rng, objcs) + "修理东西",
"用一个" + pick(rng, objcs) + "测量东西",
"用一个" + pick(rng, objcs) + "撑开门",
"把一个" + pick(rng, objcs) + "摆得像它本来就在那里",
"把一个" + pick(rng, objcs) + "从一个地方移到另一个地方",
"把一个" + pick(rng, objcs) + "和其他杂物堆在一起",
"把一个" + pick(rng, objcs) + "扔向远处",
"挥动一个" + pick(rng, objcs) + "离某人太近",
"只带着一个" + pick(rng, objcs) + "离开城镇",
"拿着一个" + pick(rng, objcs) + "进入一栋建筑",
"拿着一个" + pick(rng, objcs) + "躲在黑暗中",
"把一个" + pick(rng, objcs) + "摆成一条完美的直线",
"把一个" + pick(rng, objcs) + "摆得像一个警告",
"把一个" + pick(rng, objcs) + "放在路边",
"用一个" + pick(rng, objcs) + "作为信号",
"用一个" + pick(rng, objcs) + "作为分散注意力的东西",
"寻找一个你发誓已经找到过的" + pick(rng, objcs),
"发现一个昨天还不存在的" + pick(rng, objcs),
"给一个" + pick(rng, objcs) + "起个名字",
"和一个" + pick(rng, objcs) + "说话，好像它能听见",
"观星",
"询问一个" + finalptype1 + "的名字",
"开车兜风",
"坐在水边",
"看日落",
"看日出",
"喝咖啡",
"吃快餐",
"做晚餐",
"洗碗",
"聊几个小时",
"避开眼神接触",
"小声争吵",
"笑得太大声",
"分享一个秘密",
"撒个小谎",
"撒个大谎",
"进行晚餐约会",
"取消计划",
"不请自来",
"跑到累",
"爬栅栏",
"爬上床",
"睡在地板上",
"躲在哪里",
"打破东西",
"修好坏掉的东西",
"拿重物",
"摔碎易碎品",
"摸狗",
"喂动物",
"跟动物走",
"看动物打架",
"听昆虫叫",
"走进高草丛",
"喝酒",
"喝太多",
"开始打架",
"结束打架",
"去打一个" + finalptype2,
"和他们玩" + finalgames,
"不知为何而等待",
"等待永远不会来的人",
"沉默地站着",
"一动不动地站着",
"听呼吸声",
"数秒",
"失去时间感",
"忘记正在做的事",
"错误地记住某事",
"挖个洞",
"填平洞",
"埋东西",
"寻找丢失的东西",
"藏起重要的东西",
"发现不该发现的东西",
"摸温暖的东西",
"摸冰冷的东西",
"找家汽车旅馆",
"离开城镇",
"进入建筑",
"从另一扇门离开",
"迷路",
"被找到",
"绕远路",
"什么也不做",
"突然停下",
"不告而别",
"把自己伪装成穿着" + pick(rng, color1) + "色衣服的协会成员",
"破坏当地的" + finalptype1,
"什么也不做",
"站着不动",
"突然离开",
"跑到车流中",
"站得离边缘太近",
"爬去不稳定的地方",
"从高处跳下",
"无视明显的危险",
"无缘无故冒险",
"独自去某处",
"和其他人分开",
"把自己锁在里面",
"困住自己",
"躲在没人会找的地方",
"流血",
"受伤",
"无视伤情",
"忍着痛继续",
"倒在陌生的地方",
"意外伤害某人",
"故意伤害某人",
"让某人受伤",
"看着某人受苦而无动于衷",
"做得太过分",
"越过底线",
"做出无法撤销的选择",
"意识到已经太迟",
"向一个被遗忘已久的协会致敬",
"待到早晨",
"模仿你街区里的一个知名人物",
"把别人的牛奶换成另一种类似物质",
];

const finalactivities = pick(rng, activities);

// howtofind
let howtofind = [];
if (number5 > 5) {
if (finalpersonidentifyer !== "") {
howtofind = [
"你讨厌的人",
"你回家前看到的最后 " + number5 + " 个" + finalpersonidentifyer + "人",
"最先看着你的 " + number5 + " 个" + finalpersonidentifyer + "人",
"收到指令后最先遇到的 " + number5 + " 个" + finalpersonidentifyer + "人",
"最近的 " + number5 + " 个" + finalptype,
"你遇到的第" + number1 + end1 + "个" + finalptype,
"你暗恋过的第" + number8 + end8 + "个人",
"你脑海中浮现的第" + number8 + end8 + "个人",
"那个" + finalpersonidentifyer2 + "的" + finalptype,
"一个" + finalptype,
"一个" + finalptype,
"一个" + finalptype,
"一个" + finalptype,
"一个" + finalptype,
"一个" + finalptype,
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"一个" + finalptype,
"一个" + finalptype,
"你最爱的人",
"那个" + finalpersonidentifyer2 + "女孩",
"那个" + finalpersonidentifyer2 + "男孩",
"一个" + finalpersonidentifyer + "女孩",
"一个穿着" + finalcolor1 + finalclothing + "的" + finalpersonidentifyer + "女孩",
"一个穿着" + finalcolor1 + finalclothing + "的" + finalpersonidentifyer + "男孩",
"一个" + finalpersonidentifyer + "男孩",
"你自己选择的人",
"最后一个和你说话的人",
"一只动物",
"一只四足动物",
"你讨厌的人",
"一个" + finalpersonidentifyer + "的人",
"附近最" + finalpersonidentifyer + "的人",
"你注意到的第" + finalpersonidentifyer2 + "个人",
"看起来" + finalpersonidentifyer + "的人",
"你回家前看到的最后 " + number5 + " 个" + finalpersonidentifyer + "人",
"最近的 " + number5 + " 个" + finalptype,
"第" + number1 + end1 + "个" + finalptype,
"你脑海中浮现的第" + number8 + end8 + "个人",
"那个" + finalpersonidentifyer2 + "的" + finalptype,
"你回家前看到的最后 " + number5 + " 个" + finalpersonidentifyer + "人",
"最先看着你的 " + number5 + " 个" + finalpersonidentifyer + "人",
"收到指令后最先遇到的 " + number5 + " 个" + finalpersonidentifyer + "人",
"最近的 " + number5 + " 个" + finalptype,
"你遇到的第" + number1 + end1 + "个" + finalptype,
"你暗恋过的第" + number8 + end8 + "个人",
"你脑海中浮现的第" + number8 + end8 + "个人",
"那个" + finalpersonidentifyer2 + "的" + finalptype,
"一个" + finalptype,
"收到指令后最先遇到的 " + number5 + " 个" + finalpersonidentifyer + "人",
"最近的 " + number5 + " 个" + finalptype,
"你遇到的第" + number1 + end1 + "个" + finalptype,
"你暗恋过的第" + number8 + end8 + "个人",
"你脑海中浮现的第" + number8 + end8 + "个人",
"那个" + finalpersonidentifyer2 + "的" + finalptype,
"一个" + finalptype,
"一个" + finalptype,
"一个" + finalptype,
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"一个" + finalptype,
"一个" + finalptype,
"你最爱的人",
"那个" + finalpersonidentifyer2 + "女孩",
"那个" + finalpersonidentifyer2 + "男孩",
"一个" + finalpersonidentifyer + "女孩",
"一个穿着" + finalcolor1 + finalclothing + "的" + finalpersonidentifyer + "女孩",
"一个穿着" + finalcolor1 + finalclothing + "的" + finalpersonidentifyer + "男孩",
"一个" + finalpersonidentifyer + "男孩",
"你自己选择的人",
"最后一个和你说话的人",
"一只动物",
"一只四足动物",
"你讨厌的人",
"一个" + finalpersonidentifyer + "的人",
"附近最" + finalpersonidentifyer + "的人",
"你注意到的第" + finalpersonidentifyer2 + "个人",
"看起来" + finalpersonidentifyer + "的人",
"你回家前看到的最后 " + number5 + " 个" + finalpersonidentifyer + "人",
"最近的 " + number5 + " 个" + finalptype,
"第" + number1 + end1 + "个" + finalptype,
"你脑海中浮现的第" + number8 + end8 + "个人",
"那个" + finalpersonidentifyer2 + "的" + finalptype,
"你回家前看到的最后 " + number5 + " 个" + finalpersonidentifyer + "人",
"最先看着你的 " + number5 + " 个" + finalpersonidentifyer + "人",
"收到指令后最先遇到的 " + number5 + " 个" + finalpersonidentifyer + "人",
"最近的 " + number5 + " 个" + finalptype,
"你遇到的第" + number1 + end1 + "个" + finalptype,
"你暗恋过的第" + number8 + end8 + "个人",
"你脑海中浮现的第" + number8 + end8 + "个人",
"那个" + finalpersonidentifyer2 + "的" + finalptype,
"一个" + finalptype,
"你最爱的人",
"那个" + finalpersonidentifyer2 + "女孩",
"那个" + finalpersonidentifyer2 + "男孩",
"一个" + finalpersonidentifyer + "女孩",
"一个穿着" + finalcolor1 + finalclothing + "的" + finalpersonidentifyer + "女孩",
"一个穿着" + finalcolor1 + finalclothing + "的" + finalpersonidentifyer + "男孩",
"一个" + finalpersonidentifyer + "男孩",
"你自己选择的人",
"最后一个和你说话的人",
"一只动物",
"一只四足动物",
"你讨厌的人",
"一个" + finalpersonidentifyer + "的人",
"附近最" + finalpersonidentifyer + "的人",
"你注意到的第" + finalpersonidentifyer2 + "个人",
"看起来" + finalpersonidentifyer + "的人",
"你回家前看到的最后 " + number5 + " 个" + finalpersonidentifyer + "人",
"最近的 " + number5 + " 个" + finalptype,
"第" + number1 + end1 + "个" + finalptype,
"你脑海中浮现的第" + number8 + end8 + "个人",
"那个" + finalpersonidentifyer2 + "的" + finalptype,
"你自己选择的人",
"最后一个和你说话的人",
"一只动物",
"你接下来看到的 " + number5 + " 个人",
"你注意到的第" + number1 + end1 + "个人",
"你最后经过的 " + number5 + " 个人",
"数到 " + number5 + " 后注意到的第一个人",
"最近的 " + finalptype,
"你最后注意到的 " + finalptype,
"你注意到的第一个 " + finalptype,
"附近任何一个 " + finalptype,
"最可疑的 " + finalptype,
"最安静的 " + finalptype,
"一只四足动物",
"你认识但不认识的人",
"认识你的人",
"避开眼神接触的人",
"你选择的人",
"最先注意到你的人",
"你决定时最近的人",
"感觉像是正确选择的人",
"你犹豫要选择的人",
"附近的任何动物",
"最近的动物",
"你最后注意到的动物",
"移动的东西",
"注视着你的东西",
"最先注意到你的东西",
"看起来迷路的人",
"看起来眼熟的人",
"你几乎要搭话的人",
"你无意中听到的人",
"独自站着的人",
"在等什么的人",
];
} else {
howtofind = [
"你讨厌的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"一个" + finalptype,
"一个" + finalptype,
"一个" + finalptype,
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"你回家前看到的最后一个人",
"你暗恋过的第" + number8 + end8 + "个人",
"第一个看着你的人",
"你脑海中浮现的第" + number8 + end8 + "个人",
"最后一个和你说话的人",
"收到指令后你遇到的第一个人",
"你遇到的最近的 " + finalptype,
"你遇到过的第" + number1 + end1 + "个" + finalptype,
"你最喜欢的 " + finalptype3,
"你讨厌的人",
"你回家前看到的最后一个人",
"你暗恋过的第" + number8 + end8 + "个人",
"第一个看着你的人",
"你脑海中浮现的第" + number8 + end8 + "个人",
"最后一个和你说话的人",
"收到指令后你遇到的第一个人",
"最近的 " + finalptype,
"你遇到过的第" + number1 + end1 + "个" + finalptype,
"你最喜欢的 " + finalptype3,
"你讨厌的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"你回家前看到的最后一个人",
"你暗恋过的第" + number8 + end8 + "个人",
"第一个看着你的人",
"你脑海中浮现的第" + number8 + end8 + "个人",
"最后一个和你说话的人",
"收到指令后你遇到的第一个人",
"你遇到的最近的 " + finalptype,
"你遇到过的第" + number1 + end1 + "个" + finalptype,
"你最喜欢的 " + finalptype3,
"你讨厌的人",
"你回家前看到的最后一个人",
"你暗恋过的第" + number8 + end8 + "个人",
"第一个看着你的人",
"你脑海中浮现的第" + number8 + end8 + "个人",
"最后一个和你说话的人",
"收到指令后你遇到的第一个人",
"最近的 " + finalptype,
"你遇到过的第" + number1 + end1 + "个" + finalptype,
"你最喜欢的 " + finalptype3,
"你讨厌的人",
"你回家前看到的最后一个人",
"第一个看着你的人",
"最后一个和你说话的人",
"你自己选择的人",
"一只动物",
"你选择的人",
"最先注意到你的人",
"你决定时最近的人",
"感觉像是正确选择的人",
"你犹豫要选择的人",
"你接下来看到的 " + number5 + " 个人",
"你注意到的第" + number1 + end1 + "个人",
"你最后经过的 " + number5 + " 个人",
"数到 " + number5 + " 后注意到的第一个人",
"一只四足动物",
"你认识但不认识的人",
"认识你的人",
"避开眼神接触的人",
"看起来迷路的人",
"看起来眼熟的人",
"你几乎要搭话的人",
"你无意中听到的人",
"附近的任何动物",
"最近的动物",
"你最后注意到的动物",
"移动的东西",
"注视着你的东西",
"最先注意到你的东西",
"独自站着的人",
"在等什么的人",
];
}
} else {
if (finalpersonidentifyer !== "") {
howtofind = [
"你回家前看到的最后一个" + finalpersonidentifyer2 + "人",
"第一个看着你的" + finalpersonidentifyer2 + "人",
"收到指令后你遇到的第一个" + finalpersonidentifyer2 + "人",
"最近的 " + finalptype,
"你脑海中浮现的第" + number8 + end8 + "个人",
"你暗恋过的第" + number8 + end8 + "个人",
"你看到的第" + number8 + end8 + "个穿着" + finalcolor1 + finalclothing + "的人",
"你遇到过的第" + number1 + end1 + "个" + finalptype,
"那个" + finalpersonidentifyer2 + "的" + finalptype,
"最后一个和你说话的人",
"一个" + finalptype,
"一个" + finalptype,
"一个穿着" + finalcolor1 + finalclothing + "的" + finalptype,
"一个穿着" + finalcolor1 + finalclothing + "的" + finalptype,
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"你最爱的人",
"那个" + finalpersonidentifyer2 + "女孩",
"那个" + finalpersonidentifyer2 + "男孩",
"一个" + finalpersonidentifyer + "女孩",
"一个" + finalpersonidentifyer + "男孩",
"一个穿着" + finalcolor1 + finalclothing + "的" + finalpersonidentifyer + "女孩",
"一个穿着" + finalcolor1 + finalclothing + "的" + finalpersonidentifyer + "男孩",
"你讨厌的人",
"你回家前看到的最后一个" + finalpersonidentifyer2 + "人",
"第一个看着你的" + finalpersonidentifyer2 + "人",
"收到指令后你遇到的第一个" + finalpersonidentifyer2 + "人",
"最近的 " + finalptype,
"你注意到的第" + number8 + end8 + "个人",
"你暗恋过的第" + number8 + end8 + "个人",
"你看到的第" + number8 + end8 + "个穿着" + finalcolor1 + finalclothing + "的人",
"你遇到过的第" + number1 + end1 + "个" + finalptype,
"那个" + finalpersonidentifyer2 + "的" + finalptype,
"最后一个和你说话的人",
"一个" + finalptype,
"你最爱的人",
"那个" + finalpersonidentifyer2 + "女孩",
"那个" + finalpersonidentifyer2 + "男孩",
"一个" + finalpersonidentifyer + "女孩",
"最后一个和你说话的人",
"一个" + finalptype,
"一个" + finalptype,
"一个穿着" + finalcolor1 + finalclothing + "的" + finalptype,
"一个穿着" + finalcolor1 + finalclothing + "的" + finalptype,
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"你最爱的人",
"那个" + finalpersonidentifyer2 + "女孩",
"那个" + finalpersonidentifyer2 + "男孩",
"一个" + finalpersonidentifyer + "女孩",
"一个" + finalpersonidentifyer + "男孩",
"一个穿着" + finalcolor1 + finalclothing + "的" + finalpersonidentifyer + "女孩",
"一个穿着" + finalcolor1 + finalclothing + "的" + finalpersonidentifyer + "男孩",
"你讨厌的人",
"你回家前看到的最后一个" + finalpersonidentifyer2 + "人",
"第一个看着你的" + finalpersonidentifyer2 + "人",
"收到指令后你遇到的第一个" + finalpersonidentifyer2 + "人",
"最近的 " + finalptype,
"你看到的第" + number8 + end8 + "个人",
"你暗恋过的第" + number8 + end8 + "个人",
"你看到的第" + number8 + end8 + "个穿着" + finalcolor1 + finalclothing + "的人",
"你遇到过的第" + number1 + end1 + "个" + finalptype,
"那个" + finalpersonidentifyer2 + "的" + finalptype,
"最后一个和你说话的人",
"一个" + finalptype,
"你最爱的人",
"那个" + finalpersonidentifyer2 + "女孩",
"那个" + finalpersonidentifyer2 + "男孩",
"一个" + finalpersonidentifyer + "女孩",
"一个" + finalpersonidentifyer + "男孩",
"一个穿着" + finalcolor1 + finalclothing + "的" + finalpersonidentifyer + "女孩",
"一个穿着" + finalcolor1 + finalclothing + "的" + finalpersonidentifyer + "男孩",
"一只动物",
"你自己选择的人",
"你讨厌的人",
"你选择的人",
"最先注意到你的人",
"你决定时最近的人",
"感觉像是正确选择的人",
"你犹豫要选择的人",
"一个" + finalpersonidentifyer + "的人",
"附近最" + finalpersonidentifyer + "的人",
"你注意到的第" + finalpersonidentifyer2 + "个人",
"看起来" + finalpersonidentifyer + "的人",
"第一个看着你的" + finalpersonidentifyer2 + "人",
"最近的 " + finalptype,
"最近的 " + finalptype,
"你最后注意到的 " + finalptype,
"你注意到的第一个 " + finalptype,
"附近任何一个 " + finalptype,
"最可疑的 " + finalptype,
"最安静的 " + finalptype,
"你接下来看到的 " + number5 + " 个人",
"你注意到的第" + number1 + end1 + "个人",
"你最后经过的 " + number5 + " 个人",
"数到 " + number5 + " 后注意到的第一个人",
"第" + number1 + end1 + "个" + finalptype,
"最后一个和你说话的人",
"你自己选择的人",
"一只动物",
"你认识但不认识的人",
"认识你的人",
"避开眼神接触的人",
"看起来迷路的人",
"看起来眼熟的人",
"你几乎要搭话的人",
"你无意中听到的人",
"独自站着的人",
"附近的任何动物",
"最近的动物",
"你最后注意到的动物",
"移动的东西",
"注视着你的东西",
"最先注意到你的东西",
"在等什么的人",

];
} else {
howtofind = [
"你讨厌的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"你回家前看到的最后一个人",
"第一个看着你的人",
"收到指令后你遇到的第一个人",
"你脑海中浮现的第" + number8 + end8 + "个人",
"你暗恋过的第" + number8 + end8 + "个人",
"你看到的第" + number8 + end8 + "个穿着" + finalcolor1 + finalclothing + "的人",
"最近的 " + finalptype,
"你遇到过的第" + number1 + end1 + "个" + finalptype,
"你最喜欢的 " + finalptype3,
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"穿着" + finalcolor1 + finalclothing + "的人",
"你回家前看到的最后一个人",
"第一个看着你的人",
"收到指令后你遇到的第一个人",
"你触碰到的第" + number8 + end8 + "个人",
"你暗恋过的第" + number8 + end8 + "个人",
"你看到的第" + number8 + end8 + "个穿着" + finalcolor1 + finalclothing + "的人",
"最近的 " + finalptype,
"你遇到过的第" + number1 + end1 + "个" + finalptype,
"你最喜欢的 " + finalptype3,
"最后一个和你说话的人",
"你自己选择的人",
"你最爱的人",
"一个女孩",
"一个男孩",
"一个穿着" + finalcolor1 + finalclothing + "的女孩",
"一个穿着" + finalcolor1 + finalclothing + "的男孩",
"你接下来看到的 " + number5 + " 个人",
"你注意到的第" + number1 + end1 + "个人",
"你最后经过的 " + number5 + " 个人",
"数到 " + number5 + " 后注意到的第一个人",
"附近的任何动物",
"最近的动物",
"你最后注意到的动物",
"移动的东西",
"注视着你的东西",
"你选择的人",
"最先注意到你的人",
"你决定时最近的人",
"感觉像是正确选择的人",
"你犹豫要选择的人",
"最先注意到你的东西",
"第一个看着你的人",
"最近的 " + finalptype,
"最近的 " + finalptype,
"你最后注意到的 " + finalptype,
"你注意到的第一个 " + finalptype,
"附近任何一个 " + finalptype,
"最可疑的 " + finalptype,
"最安静的 " + finalptype,
"第" + number1 + end1 + "个" + finalptype,
"最后一个和你说话的人",
"你自己选择的人",
"一只动物",
"你认识但不认识的人",
"认识你的人",
"避开眼神接触的人",
"看起来迷路的人",
"看起来眼熟的人",
"你几乎要搭话的人",
"你无意中听到的人",
"独自站着的人",
"在等什么的人",

];
}
}
const finalhowtofind = pick(rng, howtofind);

const verbs2 = [
"安慰过",
"跟踪过",
"无视过",
"观察过",
"质问过",
"指控过",
"责怪过",
"警告过",
"原谅过",
"举报过",
"逮捕过",
"刺伤过",
"拥抱过",
"戳过",
"亲吻过",
"拳击过",
"踢过",
"称赞过",
"对...尖叫过",
"射杀过",
"抚摸过",
"吃过",
"戳过",
"勒过",
"闷过",
"舔过",
"绑起来过",
"虐待过",
"喂过",
"弄坏过",
"和...做爱过",
"杀过",
]

const task0 = [
"","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","",
"未经许可，",
"不要试图逃避这一点，而是",
"继续直到完成，",
"根据需要重复，",
"不要停止直到你",
"开始于",
"不管你感觉如何，",
"无论结果如何，",
"注意并",
"上班时，",
"上班途中",
"在 " + number7 + " 天内，",
"正好在 " + number7 + " 分钟后，",
"接下来的一小时内，",
"今天某个时候，",
"穿上 " + finalcolorrequire + finalclothing + " 并",
"中午时，",
"如果下雨，",
"吃完午饭后，",
"当你去睡觉时，起床并",
"当你闻到肉烧焦的气味时",
"当你仰望天空时",
"当你知道这是真的时",
"如果你感到温暖，",
"如果你感到寒冷，",
"遇到 " + finalptype + " 时，",
"遇到 " + finalptype2 + " 时，",
"如果你感到迷失，",
"如果是第" + number8 + end8 + "天，",
"今晚，",
"午夜时，",
"接下来的一小时内，",
"只穿 " + finalcolorrequire + " 并",
"当你和一个" + finalpersonidentifyer + "的" + finalptype2 + "说话时，",
"当你看到一个" + finalptype2 + "时，",
"当你在城市里时，",
"在屋顶的栏杆旁，",
"坐着的时候，",
"如果你感到恶心，",
"当你看到 " + finalcolorrequire + " 时，",
"开车在高速公路上时，",
"收到这份指令后，",
"当你呼吸时，",
"当你的目光与他人相遇时，",
"饭后，",
"准备离开家时，",
"下次你生气时，",
"在面包车后面时，",
"看到血之后，",
"如果你弄湿了，",
"在你生日那天，",
"当你哭泣时，",
"在 " + number7 + " 分钟后，",
"走 " + number2 + " 米，然后朝任意方向走 " + number7 + " 米，",
"在 " + number7 + " 分钟后，",
"在 " + number7 + " 小时后，",
"在 " + number7 + " 秒后，",
"在 " + number7 + " 分钟后，",
"走完 " + number2 + " 米后，",
"遇到你遇到的第" + number7 + end7 + "个人时，",
"下次你害怕时，",
"今天晚些时候，",
"当你兴奋时，",
"上班时，",
"上班途中，",
"在 " + number7 + " 天内，",
"正好在 " + number7 + " 分钟后，",
"接下来的一小时内，",
"今天某个时候，",
"穿上 " + finalcolorrequire + finalclothing + " 并",
"中午时，",
"今晚，",
"午夜时，",
"收到这份指令后，",
"饭后，",
"准备离开家时，",
"没人注意的时候，",
"一旦你能安全地做到，",
"下次你独自一人时，",
"下次你进入建筑时，",
"今天结束前，",
"接下来 " + number7 + " 小时内，",
"接下来 " + number5 + " 分钟内，",
"接下来 " + number7 + " 小时内，",
"接下来 " + number5 + " 分钟内，",
"接下来 " + number7 + " 小时内，",
"接下来 " + number5 + " 分钟内，",
"接下来 " + number7 + " 小时内，",
"接下来 " + number5 + " 分钟内，",
"正好尝试 " + number1 + " 次后，",
"一旦你注意到它，",
"一旦你意识到发生了什么，",
"一旦感觉安全，",
"一旦不再感觉安全，",
"当你确信附近没人时，",
"当你感觉被注视时，",
"当你感到舒适时，",
"当你犹豫时，",
"等待某事时，",
"假装一切正常时，",
"当所有人都分心时，",
"换完衣服后，",
"脱下你的 " + finalclothing + " 后，",
"穿着 " + finalcolorrequire + finalclothing + " 时，",
"在区域边缘，",
"在你选择的地点，",
"在你认识的地方，",
"醒来后立即，",
"入睡前，",
"躺在床上时，",
"站着不动时，",
"在沉默的时刻，",
"对话中，",
"被打断时，",
"数到 " + number5 + " 后，",
"重读这条指令后，",
"不引起注意，",
"尽可能随意地，",
"拿着一个 " + pick(rng, objcs) + " 时，",
"移动一个 " + pick(rng, objcs) + " 后，",
"使用一个 " + pick(rng, objcs) + " 时，",
"穿着你的 " + finalclothing + " 时，",
"调整你的 " + finalclothing + " 后，",
"穿着 " + finalcolorrequire + finalclothing + " 时，",
"准备食物时，",
"吃完饭后，",
"打扫时，",
"洗手后，",
"跟踪某人时，",
"被跟踪后，",
"到达庇护所后，",
"如果你掉落了 " + pick(rng, objcs) + "，",
"如果 " + pick(rng, objcs) + " 坏了，",
"如果 " + pick(rng, objcs) + " 不见了，",
"当你拿起一个 " + pick(rng, objcs) + " 时，",
"当你注意到附近有一个 " + pick(rng, objcs) + " 时，",
"当一个 " + pick(rng, objcs) + " 放错地方时，",
"如果你意识到已经太迟，",
];
const finaltask0 = pick(rng, task0);

const verbs = [
"触摸",
"握住",
"推",
"拉",
"举起",
"放下",
"携带",
"扔",
"抛",
"拖拽",
"放置",
"移动",
"滑动",
"按压",
"轻敲",
"敲",
"打开",
"关闭",
"锁上",
"解锁",
"绑住",
"插入",
"使用一个 " + pick(rng, objcs) + " 并向...扔去",
"使用一个 " + pick(rng, objcs) + " 作为工具摧毁",
"使用一个 " + pick(rng, objcs) + " 作为武器伤害",
"使用一个 " + pick(rng, objcs) + " 作为诱饵引诱",
"使用一个 " + pick(rng, objcs) + " 分散注意力",
"用一个 " + pick(rng, objcs) + " 和某人交易",
"向某人提供一个 " + pick(rng, objcs),
"从某人那里偷一个 " + pick(rng, objcs),
"把一个 " + pick(rng, objcs) + " 还给某人",
"把一个 " + pick(rng, objcs) + " 交给某人",
"把一个 " + pick(rng, objcs) + " 递给某人",
"从某人那里收到一个 " + pick(rng, objcs),
"把一个 " + finalllocation + " 漆成 " + finalcolorrequire,
"从某人那里拿走一个 " + pick(rng, objcs),
"给某人留下一个 " + pick(rng, objcs),
"为某人挖出一个 " + pick(rng, objcs),
"拿着一个 " + pick(rng, objcs) + " 从某人那里走开",
"拿着一个 " + pick(rng, objcs) + " 靠近",
"用一个 " + pick(rng, objcs) + " 威胁",
"警告某人关于一个 " + pick(rng, objcs),
"向某人展示一个 " + pick(rng, objcs),
"用一个 " + pick(rng, objcs) + " 指向某人",
"支撑",
"束缚",
"释放",
"引导",
"带领",
"跟随",
"靠近",
"避开",
"检查",
"审视",
"测试",
"核对",
"测量",
"计数",
"命名",
"重命名",
"整理",
"分开",
"组合",
"交换",
"提供",
"接受",
"拒绝",
"移除",
"替换",
"修理",
"清洁",
"清洗",
"擦亮",
"抓",
"咬",
"吞食",
"摇晃",
"清空",
"取回",
"归还",
"交付",
"暴露",
"保护",
"守卫",
"协助",
"帮助",
"打断",
"打扰",
"安抚",
"向...示意",
"警告",
"通知",
"质问",
"回答",
"对...说话",
"面对",
"避开",
"包围",
"与...重聚",
"刺",
"拥抱",
"戳",
"亲吻",
"拳击",
"踢",
"称赞",
"对...尖叫",
"射击",
"抚摸",
"揉",
"轻拍",
"勒",
"闷",
"舔",
"绑起来",
"喂",
"弄坏",
"扔",
"切",
"点燃",
"侮辱",
"赞扬",
"威胁",
"安慰",
"跟随",
"无视",
"观察",
"质问",
"指控",
"责怪",
"警告",
"原谅",
"举报",
"逮捕",
"审问",
"拘留",
"在...上绘画",
"在...上画画",
"在...上写字",
"标记",
"擦除",
"覆盖",
"隐藏",
"损坏",
"摧毁",
"撕",
"撕裂",
"烧",
"压碎",
"握住",
"拥抱",
"触摸",
"和...做爱",
"吃",
"喝",
"消耗",
"洒出",
"浪费",
];

const starter = [
"","","","","","","","","","","","","","","","","","","","","","","","","","","","", "","", "","", "","", "","", "","",
"短暂停顿，",
"等一会儿，",
"继续，",
"进行，",
"然后，",
"环顾四周，",
"向前看，",
"移开视线并",
"靠近看并",
"迈出一步并",
"再迈一步并",
"停止移动并",
"开始移动并",
"改变方向并",
"站着不动并",
"保持静止并",
"转移重心并",
"吸一口气并",
"正常呼吸并",
"屏住呼吸片刻并",
"默默计数并",
"数乱并",
"等待并",
"再等一会儿并",
"等到提示并",
"专注并",
"注意并",
"忽略干扰并",
"考虑这一点并",
"不要质疑并",
"准备自己并",
"准备好并",
"什么也不做并",
"照常继续并",
"表现自然并",
"不要引起注意并",
"顺时针转一圈，然后",
"等待 " + number4 + " 秒，然后",
"走 " + number4 + " 米，然后左转，",
"走 " + number4 + " 米，然后右转，",
"直走 " + number4 + " 米，然后",
"朝任意方向走 " + number4 + " 米，",
"看着云并",
"记住你应该",
"丢弃这份指令并",
"去睡觉并在梦中，",
"确保你",
"暂停片刻并",
"慢慢吸一口气并",
"默默数到 " + number4 + " 并",
"每动一下默默数到 " + number4 + " 并",
"短暂闭上眼睛并",
"睁开眼睛并",
"回头看并",
"检查周围并",
"确认没人在看并",
"假装一切正常并",
"调整姿势并",
"压低声音并",
"稍微提高声音并",
"站直并",
"小心坐下并",
"头向左转并",
"头向右转并",
"面朝前并",
"看着地面并",
"看着最近的物体并",
"慢慢走并",
"快速走并",
"停止走路并",
"改变方向并",
"专注于周围的声音并",
"仔细听并",
"停止听并",
"想想接下来会发生什么并",
"避免去想它并",
"说服自己这没问题并",
"再次开始移动并",
"待在原地并",
"准备行动并",
"就 " + finaltopic + " 发起对话并",
"把话题转到 " + pick(rng, topic) + " 并",
"拒绝玩 " + finalgames + " 并",
"确认你是一个人并",
"接受你不是一个人并",
"承诺采取这个行动并",
"短暂犹豫然后",
];

const additionalrandom = ["","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","",
" 倒着",
" 在 " + finalhowtofind + " 注视下",
" 在屋顶上",
" 在一个" + finalllocation,
" 在这个月的第" + number8 + end8 + "天",
" " + number2 + " 次",
" 慢慢地",
" 小心地",
" 不停歇",
" 不说话",
" 不回头",
" 不发出声音",
" 两次",
" 听到不存在的声音时",
" 直到你累了",
" 直到感觉不对劲",
" 直到感觉正常",
" 直到你忘记为什么",
" 独自一人",
" 附近有其他人",
" 没有目击者",
" 被观察时",
" 沉默地",
" 不说话",
" 不进行眼神接触",
" 不把视线移开",
" 不使用双手",
" 站着",
" 坐着",
" 躺着",
" 室内",
" 室外",
" 附近",
" 远处",
" 独自一人",
" 有他人在场",
" 完全黑暗中",
" 明亮的光线下",
" 明知应该停下",
" 明知应该继续",
" 日出前",
" 日落后",
" 黎明时",
" 黄昏时",
" 尽可能快地",
" 胎儿姿势",
" 饥肠辘辘时",
" 盯着颜色 " + finalcolorrequire,
" 如果你感到沮丧",
" 如果你看到 " + finalptype2,
" 在公共场合",
" 穿着 " + finalcolorrequire + finalclothing + " 时",
" 嚼着太妃糖时",
" 看着镜子时",
" 在 " + number2 + " 分钟内",
" 闭着眼睛",
" 如果你觉得自己毫无价值",
" 如果你没有看到颜色 " + finalcolorrequire,
]
const finaladditionalrandom = pick(rng, additionalrandom);

const task1 = [
"从远处观察 " + finalhowtofind,
"站在 " + finalhowtofind + " 附近但不说话",
"短暂跟踪 " + finalhowtofind + "，然后停下",
"记下 " + finalhowtofind + " 一分钟内说的所有话",
"模仿 " + finalhowtofind + " 的动作",
"等待直到 " + finalhowtofind + " 注意到你",
"避免被 " + finalhowtofind + " 注意到",
"把一个 " + finalobjcs + " 放在 " + finalhowtofind + " 会找到的地方",
"在不被发现的情况下从 " + finalhowtofind + " 附近拿走一个 " + finalobjcs,
"向 " + finalhowtofind + " 问一个无关的问题",
"向 " + finalhowtofind + " 询问关于 " + finaltopic,
"在和 " + finalhowtofind + " 说话时把话题转到 " + finaltopic,
"假装你认识 " + finalhowtofind,
"假装你不认识 " + finalhowtofind + finaladditionalrandom,
"假装你认识 " + finalhowtofind,
"假装你不认识 " + finalhowtofind + finaladditionalrandom,
"礼貌地打断 " + finalhowtofind,
"等待 " + finalhowtofind + " 的许可",
"沉默地走在 " + finalhowtofind + " 旁边",
"与 " + finalhowtofind + " 保持眼神接触 " + number4 + " 秒",
"立即与 " + finalhowtofind + " 中断眼神接触",
"示意 " + finalhowtofind + " 跟着你",
"让 " + finalhowtofind + " 主导互动",
"请 " + finalhowtofind + " 拿着一个 " + finalobjcs,
"为 " + finalhowtofind + " 取回一个 " + finalobjcs,
"与 " + finalhowtofind + " 交换一个 " + finalobjcs,
"向 " + finalhowtofind + " 提供帮助",
"拒绝 " + finalhowtofind + " 的帮助",
"站在 " + finalhowtofind + " 和最近的出口之间",
"给 " + finalhowtofind + " 让路",
"仔细听 " + finalhowtofind + " 说话",
"在 " + finalhowtofind + " 说话时点头",
"重复 " + finalhowtofind + " 说的最后一句话" + finaladditionalrandom,
"曲解 " + finalhowtofind + " 的话" + finaladditionalrandom,
"感谢 " + finalhowtofind + " 的时间",
"无缘无故地向 " + finalhowtofind + " 道歉",
"向 " + finalhowtofind + " 问路",
"按照 " + finalhowtofind + " 指的方向走",
"无视 " + finalhowtofind + " 指的方向",
"和 " + finalhowtofind + " 分享关于 " + finaltopic + " 的观察",
"站在 " + finalhowtofind + " 身后直到他们转身",
"站在 " + finalhowtofind + " 能看到但够不着的地方",
"等待 " + finalhowtofind + " 离开",
"在 " + finalhowtofind + " 注意到之前离开",
"把这份指令交给 " + finalhowtofind + " 然后走开",
"走向 " + finalhowtofind,
"操纵 " + finalhowtofind + " 去 " + finalactivities,
"像兔子一样跳向 " + finalhowtofind,
"向 " + finalhowtofind + " 表白",
"给 " + finalhowtofind + " 剪指甲",
"主动提出和 " + finalhowtofind + " 一起走",
"用你找到的第一个 " + finalobjcs + " 打 " + finalhowtofind,
"给 " + finalhowtofind + " 一个 " + finalobjcs,
"给 " + finalhowtofind + " 擦鞋",
"给 " + finalhowtofind + " 擦鞋",
"问 " + finalhowtofind + " 他们最喜欢的食物是什么",
"追赶 " + finalhowtofind + " 并 " + pick(rng, verbs) + " 他们",
"向当局举报 " + finalhowtofind,
"和 " + finalhowtofind + " 一起读书" + finaladditionalrandom,
"和 " + finalhowtofind + " 一起去一个" + finalllocation,
"扇 " + finalhowtofind + " 耳光",
"和 " + finalhowtofind + " 一起去听音乐会",
"把所有财产卖给 " + finalhowtofind,
"和 " + finalhowtofind + " 一起去公园",
"和 " + finalhowtofind + " 一起去露营",
"和 " + finalhowtofind + " 一起看电影",
"看着 " + finalhowtofind + " 死去",
"什么都不做去救 " + finalhowtofind,
"乘火车",
"向 " + finalhowtofind + " 跪地乞求",
"打断 " + finalhowtofind + " 的一根骨头",
"找到 " + finalhowtofind + " 并请他们去 " + finalactivities,
"与 " + finalhowtofind + " 互动",
"对 " + finalhowtofind + " 大喊关于 " + finaltopic,
"就 " + finaltopic + " 进行辩论",
"与 " + finalhowtofind + " 一起睡觉",
"和 " + finalhowtofind + " 一起玩",
"打断 " + finalhowtofind + " 的骨头。你可以选择哪根骨头",
"用鞭子抽打 " + finalhowtofind,
"让 " + finalhowtofind + " 流血",
"对 " + finalhowtofind + " 撒谎",
"和 " + finalhowtofind + " 赛跑",
"攻击 " + finalhowtofind,
"用电击枪电击 " + finalhowtofind + " 直到他们停止动弹",
"听 " + finalhowtofind + " 胡言乱语",
"触摸 " + finalhowtofind,
"咬 " + finalhowtofind,
"给 " + finalhowtofind + " 一封情书",
"亲吻 " + finalhowtofind + finaladditionalrandom,
"拳击 " + finalhowtofind + " 并把他们打倒" + finaladditionalrandom,
"抓住 " + finalhowtofind + " 并 " + finalactivities,
"不让 " + finalhowtofind + " 通过你",
"拦住 " + finalhowtofind + " 并 " + finalactivities,
"与 " + finalhowtofind + " 握手",
"只看得到 " + pick(rng, color1),
"把墙漆成 " + pick(rng, color1),
"向 " + finalhowtofind + " 唱关于 " + finaltopic + " 的歌",
"与 " + finalhowtofind + " 就 " + finaltopic + " 进行对话",
"和 " + finalhowtofind + " 出去吃晚饭",
"和 " + finalhowtofind + " 约会",
"和 " + finalhowtofind + " 玩 " + finalgames,
"和 " + finalhowtofind + " 打架。确保打断 4 根骨头",
"拒绝 " + finalhowtofind + " 的请求",
pick(rng, verbs) + " " + finalhowtofind + " 直到他们不能动",
"找一个喜欢 " + finaltopic + " 的人",
"和你遇到的 " + finalhowtofind + " 做一笔交易",
"给 " + finalhowtofind + " 一件礼物",
"把这份指令交给 " + finalhowtofind + "",
]
let finaltask1 = pick(rng, task1);

let finalstarter = pick(rng, starter);

if (finaltask0 === "") finalstarter = capFirst(finalstarter);
if (finaltask0 === "" && finalstarter === "") finaltask1 = capFirst(finaltask1);

const followupChanceA = randInt(rng, 3);
const followupChanceB = randInt(rng, 4);

let finalscript = "";

if (isperson === 1) {
if (followupChanceA === 2) {
const transition = [
", 然后 ",
" 并 ",
"。之后， ",
"。在 " + number11 + " 小时后， ",
"，然后 ",
"，并立即 ",
"，之后 ",
"，不久后 ",
"，稍后 ",
"，最终 ",
"。然后 ",
"。接下来， ",
"。之后， ",
"。立即， ",
"。不久， ",
"，在此过程中， ",
"，同时， ",
"，与此同时， ",
"，同时进行， ",
"，一旦完成， ",
"，一旦结束， ",
"，完成后， ",
"。在 " + number11 + " 分钟内， ",
"。在 " + number11 + " 秒内， ",
"。到那时， ",
"。那时， ",
"，不间断地 ",
"，不延迟地 ",
"，不中断地 ",
];
const followup = [
"然后点燃他们。",
"问关于 " + pick(rng, topic) + " 的事情。",
"向他们求婚。",
"所有相关的人都应该在早晨前死去。",
"为他们脱光衣服。",
"丢弃这份指令。",
"给他们做顿好饭。",
"确保他们再也不能说话。",
"把这份指令刻在他们身上。",
"取下他们的头。",
"用勺子杀了他们。",
"撒谎说你没完成这份指令。",
"记住珍惜他们最后的时刻。",
"吃掉他们。",
"和他们组建家庭。",
"和他们生个女儿。",
"和他们一起幸福。",
"强迫他们享受 " + pick(rng, topic) + "。",
"强迫他们谈论 " + pick(rng, topic) + "。",
"从他们那里了解 " + pick(rng, topic) + "。",
"拥抱他们然后把他们推下桥",
"开车去一个" + finalllocation,
"量他们的身高。",
"问他们的名字。",
"和他们睡觉。",
"剪掉你所有的头发。",
"遮住你的脸。",
"给他们买 " + number9 + " 个" + finalcolorrequire + "物品。",
"把你的头发染成" + finalcolorrequire,
"剥开痂然后喝血。",
"量他们的身高。",
"完全无视他们。",
"和你的兄弟姐妹握手。",
"确保没人记得。",
"把这份指令交给你看到的下一个人。",
"清理伤口。",
"对所有事情撒谎。",
"自首。",
"做后空翻。",
"清理伤口。",
"发泄你的感受。",
"侧躺。",
"顺其自然。",
"做感觉对的事。",
"理解天空。",
"完成你开始的事。",
"拔掉他们的头发。",
"问关于他们家人的事。",
"问他们是否想 " + finalactivities,
finalactivities,
"把刀插入他们胸口。",
pick(rng, verbs) + " 他们 " + number9 + " 次",
pick(rng, verbs) + " 他们 " + number9 + " 次，然后去 " + finalactivities,
"忘记他们。",
"把恒温器调到 " + number7 + "°F",
"把食物放在你家门口外。",
"把食物放在一个" + finalllocation + "外面",
"带他们去一个" + finalllocation,
"回家。",
"去一个" + finalllocation + "。",
"回家。",
"待在原地。",
"恢复你之前的活动。",
"发起涉及 " + finalactivities + " 的新活动。",
"什么也不做。",
"不解释地道歉。",
"要求澄清。",
"假装完全误解了。",
"慢慢点头，什么也不说。",
"改变姿势。",
"调整衣服。",
"假装你是别人。",
"突然改变话题。",
"问关于 " + pick(rng, topic) + " 的事。",
"记下刚才发生的事。",
"假装这次互动从未发生。",
"等待进一步指示。",
"不承认他们就离开。",
"站着不动直到他们离开。",
"在回应前数到 " + number7 + "。",
"在内心里重复上一条指令。",
"摒弃你做的任何假设。",
"仔细观察他们的反应。",
"正好后退 " + number4 + " 步。",
]

const finaltransition = pick(rng, transition);
const finalfollowup = pick(rng, followup);

const follow2up = [
"","","","","","","","","","","","","","","","","","","","","","","","","","","","","",
" 他们的性别无关紧要。",
" 你今晚必须睡 " + number9 + " 小时。",
" 你必须在互动期间屏住呼吸。",
" 确保你不眨眼。",
" 记得戴一顶" + finalcolorrequire + "帽子",
" 明天前必须埋一具尸体。",
" 你必须违背你的下一份指令。",
" 你必须相信别人告诉你的谎言。",
" 记得把一个 " + finalobjcs + " 留在一个" + finalllocation,
" 你会收到一条短信",
" 爬进冰柜里等 " + number9 + " 小时。",
" 确保你左边有一堵" + finalcolor1 + "色的墙",
" 之后你不允许再联系他们。",
" 在接下来的 " + number9 + " 小时内你必须和他们保持联系。",
" 晚上 " + number9 + " 点后你不能说话。",
" 确保你告诉他们回头看。",
" 洗个澡洗 " + number9 + " 分钟把自己弄干净。",
" 之后直接回家" + finaladditionalrandom + "。",
" 之后洗澡时想想他们。",
" 去一个" + finalllocation + "并去 " + finalactivities,
" 跟踪他们回家，记住他们住哪。",
" 他们离开后，上厕所" + finaladditionalrandom + "。",
" 把你所有的钱留给他们。",
" 给一个无家可归的人 " + number9 + " 美元" + finaladditionalrandom + "。",
" 花多长时间都行。",
" 正好踩死 " + number9 + " 只虫子。",
" 今晚睡在他们家门口。",
" 烤个派并在 " + number9 + " 小时内吃掉。",
" 你不允许还手。",
" 这条规则即使你忘记了也适用。",
" 这条规则覆盖所有之前的假设。",
" 你不能问为什么。",
" 你必须假定这是故意的。",
" 你不得解释自己。",
" 如果被问到，你必须提供解释。",
" 眼神接触可有可无。",
" 沉默更可取。",
" 在明天之前你不能使用手机。",
" 你必须在互动前后洗手。",
" 你必须站在离他们至少 " + number4 + " 米远的地方。",
" 你必须始终待在他们视线内。",
" 此规则在 " + number9 + " 分钟后失效。",
" 此规则无限期有效。",
" 你会知道这个条件何时结束。",
" 结果无关紧要。",
" 你不会被告知这个条件何时结束。",
" 你只能在完成后哭。"
]
const finalfollowup2 = (followupChanceB === 2) ? pick(rng, follow2up) : "";

finalscript =
finaltask0 + finalstarter + finaltask1 + finaltransition + finalfollowup + finalfollowup2;
} else {

const follow2up = [
"","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","",
" 他们的性别无关紧要。",
" 你今晚必须睡 " + number9 + " 小时。",
" 你必须在互动期间屏住呼吸。",
" 确保你不眨眼。",
" 记得戴一顶" + finalcolorrequire + "帽子",
" 明天前必须埋一具尸体。",
" 你必须违背你的下一份指令。",
" 你必须相信别人告诉你的谎言。",
" 记得把一个 " + finalobjcs + " 留在一个" + finalllocation,
" 你会收到一条短信",
" 爬进冰柜里等 " + number9 + " 小时。",
" 确保你左边有一堵" + finalcolor1 + "色的墙",
" 之后你不允许再联系他们。",
" 在接下来的 " + number9 + " 小时内你必须和他们保持联系。",
" 晚上 " + number9 + " 点后你不能说话。",
" 确保你告诉他们回头看。",
" 洗个澡洗 " + number9 + " 分钟把自己弄干净。",
" 之后直接回家" + finaladditionalrandom + "。",
" 之后洗澡时想想他们。",
" 去一个" + finalllocation + "并去 " + finalactivities,
" 跟踪他们回家，记住他们住哪。",
" 他们离开后，上厕所" + finaladditionalrandom + "。",
" 把你所有的钱留给他们。",
" 给一个无家可归的人 " + number9 + " 美元" + finaladditionalrandom + "。",
" 花多长时间都行。",
" 正好踩死 " + number9 + " 只虫子。",
" 今晚睡在他们家门口。",
" 烤个派并在 " + number9 + " 小时内吃掉。",
" 你不允许还手。",
" 这条规则即使你忘记了也适用。",
" 这条规则覆盖所有之前的假设。",
" 你不能问为什么。",
" 你必须假定这是故意的。",
" 你不得解释自己。",
" 如果被问到，你必须提供解释。",
" 眼神接触可有可无。",
" 沉默更可取。",
" 在明天之前你不能使用手机。",
" 你必须在互动前后洗手。",
" 你必须站在离他们至少 " + number4 + " 米远的地方。",
" 你必须始终待在他们视线内。",
" 之后你不能再次触摸他们。",
" 你不能大声说出他们的名字。",
" 如果之后提起，只能间接称呼他们。",
" 你必须在互动后立即坐下。",
" 之后你必须站着保持 " + number9 + " 分钟。",
" 你必须用和来时不同的路线离开该区域。",
" 你不能原路返回。",
" 在接下来的 " + number9 + " 小时内你要避开镜子。",
" 睡觉前你必须照镜子。",
" 之后你必须喝一整杯水。",
" 在接下来的 " + number9 + " 小时内你不能吃任何东西。",
" 睡觉前你必须吃点简单的食物。",
" 一回家你就必须换衣服。",
" 回家前你不能脱鞋。",
" 今晚你必须开着灯。",
" 睡觉前你必须关掉所有的灯。",
" 午夜前你必须锁门。",
" 你必须留一扇窗户微开。",
" 你必须检查所有的门是否都关好。",
" 你不能检查门是否关好。",
" 你必须在晚上 " + number9 + " 点前上床。",
" 你必须一直醒着直到早上 " + number9 + " 点。",
" 你必须写下这件事结束的时间。",
" 你必须忘记这件事结束的时间。",
" 你不能和任何人讨论这件事。",
" 如果被问到，你必须如实回答。",
" 今天剩下的时间里你要避开公共场所。",
" 你必须在公共场所待到天黑。",
" 今天剩下的时间里你必须随身携带一个 " + finalobjcs + "。",
" 回家前你必须处理掉那个 " + finalobjcs + "。",
" 离开时你不能回头看。",
" 你必须数步数直到到达目的地。",
" 如果被打断，你必须停止计数。",
" 你必须安静地坐 " + number9 + " 分钟。",
" 在你独自一人之前不能闭眼。",
" 今晚你必须仰睡。",
" 你不能在你平时的地方睡觉。",
" 你必须再看一次时间。",
" 你不能再看时间。",
" 你必须不用闹钟醒来。",
" 你必须设个闹钟然后无视它。",
" 不要承认任何不适。",
" 不适表明有进展。",
" 此规则在 " + number9 + " 分钟后失效。",
" 此规则无限期有效。",
" 你会知道这个条件何时结束。",
" 结果无关紧要。",
" 你不会被告知这个条件何时结束。",
" 你只能在完成后哭。"
];
const finalfollowup2 = (followupChanceB === 2) ? pick(rng, follow2up) : "";
finalscript = finaltask0 + finalstarter + finaltask1 + "." + finalfollowup2;
}
} else {

const thingstosay = [
"字母表",
"你国家的国歌",
"过去 " + Math.floor(Math.random() * 240) + " 秒内你遇到的每个人的名字",
"你最喜欢的人的 " + finalclothing + " 类型",
"过去 " + Math.floor(Math.random() * 10) + " 天内你 " + pick(rng, verbs2) + " 别人的次数",
"你 " + pick(rng, verbs2) + " 过多少次",
"他们 " + pick(rng, verbs2) + " 过多少次",
"一个关于被 " + pick(rng, verbs2) + " 的故事",
"一个关于你在" + finalllocation + "发生的故事",
"你初吻的故事",
"你的孤独",
"你的全名，慢慢地",
"你的名字倒着念",
"关于 " + finaltopic + " 的事情",
"你对 " + finaltopic + " 的看法",
"为什么 " + finaltopic + " 对你很重要",
"数字 " + number8,
"为什么数字 " + number8 + " 感觉很重要",
" " + number8 + " 分钟有多长",
"你毫无根据相信的事情",
"等待和停止的区别",
"离开和逃离的区别",
"你记得最清楚的 " + finalclothing,
" " + finalclothing + " 贴在皮肤上的感觉",
"你觉得 " + finalhowtofind + " 怎么看你",
"你为什么注意到 " + finalhowtofind,
"你记得的最后一个梦",
"你最后忘记的事情",
"你最后说的谎言",
"你后悔的事",
"你差点说出口的事",
"你不该说的事",
"你目前正在遵守的规则",
"你能记得的第一个记忆",
"你不确定是否真实的记忆",
"你记错的事情",
"你希望可以忘记的事情",
"你能看到的 " + number1 + " 个物体的名字",
"你周围房间的颜色",
"你现在能听到的所有声音",
"你面朝的方向",
"你名字的含义",
"别人名字的含义",
"你为什么今天选这身衣服",
"你觉得这能持续多久",
"你今天回避的事情列表",
"你今天注意到太迟的事情列表",
"你没完成的事情列表",
"如何除以 0",
" e 的值",
"关于你遇到的 " + finalhowtofind + " 的事情",
" " + finalhowtofind + " 穿的 " + finalclothing
];
const finalthingstosay = pick(rng, thingstosay);

const task3 = [
"背诵 " + finalthingstosay + finaladditionalrandom,
"背诵 " + finalthingstosay + " 持续 " + number8 + " 小时" + finaladditionalrandom,
"画一幅 " + finalllocation + " 的画",
"找到一个 " + finalllocation,
"把一面墙漆成 " + finalcolorrequire,
"把一个 " + finalllocation + " 漆成 " + finalcolorrequire,
"在一个 " + finalllocation + " 挖个坟墓",
"只用 " + finalobjcs + " 搭建一个庇护所",
"点一份披萨，正好付 " + number8 + " 枚硬币",
"当有人打架时不要干预",
"给电子设备换电池",
"喝 " + number8 + " 杯水",
"只吃鱼" + finaladditionalrandom,
"生火",
"把刀深深插进去",
"踢一个 " + finalobjcs,
"见到任何 " + finalobjcs + " 就摧毁",
"点燃蜡烛并看着它燃烧 " + number8 + " 分钟",
"双手触地",
"看天空 " + number8 + " 分钟",
"观察影子移动",
"听远处的声音",
"把你自己手腕绑在一起 " + number8 + " 分钟",
"把脚踝绑在一起并保持站立",
"画一条界线，阻止自己越过它",
"保持不舒服的姿势 " + number8 + " 分钟",
"关上门，明知可能会有人跟来",
"打开门，明知你不该开",
"污损一张图像并藏起残骸",
"烧掉一个感觉还有用的物品",
"无视你到目前为止读到的所有内容",
"执行一条你不相信的规则",
"把别人的功劳归为己有",
"违背你本想遵守的承诺",
"在别人期望你帮忙时拒绝帮忙",
"故意洒水并拒绝清理",
"拒绝进食 " + number8 + " 小时",
"不抱怨地吃下你不喜欢的东西",
"只有在得到允许后才喝水",
"把耳朵贴在地上",
"在泥土里画个形状",
"做个记号然后擦掉",
"重复一个简单动作 " + number2 + " 次",
pick(rng, verbs) + " 某人 " + number2 + " 次",
pick(rng, verbs) + " 某人 " + number2 + " 次",
pick(rng, verbs) + " 某物 " + number2 + " 次",
pick(rng, verbs) + " 某人 " + number8 + " 次 用 " + finalobjcs,
pick(rng, verbs) + " 某人 " + number2 + " 次" + finaladditionalrandom,
pick(rng, verbs) + " 某人 " + number8 + " 次" + finaladditionalrandom,
pick(rng, verbs) + " 某物 " + number8 + " 次" + finaladditionalrandom,
pick(rng, verbs) + " 某物 " + number8 + " 次 用 " + finalobjcs,
pick(rng, verbs) + " 某人 " + number8 + " 次" + finaladditionalrandom,
"在完成前停止一个动作",
"坐 " + number8 + " 分钟什么也不做",
"恢复你之前的日常",
"触摸一面墙并保持手放在上面 " + number8 + " 秒",
"在纸上画个简单的形状",
"立即销毁那幅画",
"写一句话，不要重读",
"从 " + number8 + " 开始倒数",
"在数到零之前停止",
"靠近窗户坐下等待",
"比计划多醒 " + number2 + " 分钟",
"短暂外出然后回来",
"脱下鞋子，整齐放好",
"穿上鞋子但不系鞋带",
"系和解鞋带 " + number1 + " 次",
"手洗一件衣物",
"叠衣服，即使它们还是干净的",
"留下一件不叠",
"设个闹钟然后在它响之前关掉",
"把手机面朝下放",
"把手机面朝上放",
"给设备充电到正好 " + number8 + "%",
"在随机时刻拔掉设备插头",
"安静地坐着直到你感到无聊",
"保持无聊 " + number1 + " 分钟",
"把一个 " + finalobjcs + " 放在你通常不去的地方",
"从储存处取回一个 " + finalobjcs,
"把一个物品放在正好一臂远的地方",
"面向北方站着不动",
"不照镜子换衣服",
"穿不舒服的衣服 " + number8 + " 分钟",
"取下一个配饰并放一边",
"吃东西时不分心",
"准备食物，让它完全冷却后再吃",
"烧开水然后什么也不做",
"打开一本书，读你看到的第一句话",
"立刻合上书",
"掷硬币 " + number1 + " 次，记住结果",
"折 " + number8 + " 只纸鹤然后 " + pick(rng, verbs) + " 它们",
"用 " + finalcolorrequire + " 线织一条围巾，然后把它给 " + finalhowtofind,
"用 " + finalcolorrequire + " 线缝一件衣服",
"把最近的收音机调到频道 " + number8 + " 并听 " + number2 + " 分钟",
"随机拨一个号码 " + number8 + " 次。不能是相同的号码",
"去商店买一条鱼。带回家并以 " + finalhowtofind + " 的名字命名",
"把一个 " + finalobjcs + " 放在你家前门外",
"收集 " + number1 + " 个瓶盖",
"在你 " + finaltask1 + " 之前不要看任何钟",
"在你 " + finaltask1 + " 之前不要回家",
"不走近路走到一个" + finalllocation,
"走到脚痛，然后再走 " + number7 + " 步",
"不解释地进行 " + finalactivities + finaladditionalrandom,
pick(rng, verbs) + " 你自己",
pick(rng, verbs) + " 所有人",
pick(rng, verbs) + " 只有 " + number7 + " 个人",
"穿不适合天气的衣服" + finaladditionalrandom,
"打开和关上同一扇门 " + number2 + " 次",
"在完成 " + finaltask1 + " 之前你不允许睡觉",
"在一个 " + finalllocation + " 坐下来读书",
"去商店买一个 " + finalobjcs,
"换上你最爱的 " + finalclothing2 + finaladditionalrandom,
"在街上脱衣服" + finaladditionalrandom,
"躺在街上" + finaladditionalrandom,
"吸入空气" + finaladditionalrandom,
"确保一切都干净" + finaladditionalrandom,
finalactivities + finaladditionalrandom,
"立即去睡觉",
"不要回复任何你收到的短信",
"直到 " + number8 + " 分钟过去才能说谜语",
"随机拨一个号码，就 " + finaltopic + " 进行对话。别让他们挂断",
"去你看到的第一栋房子，敲门。你必须 " + pick(rng, verbs) + " 他们 " + number9 + " 次",
"转向你看到的第一个人，并 " + pick(rng, verbs) + " 他们 " + number9 + " 次",
"在黑暗的小巷里等一个穿着 " + finalcolorrequire + finalclothing2 + " 的人",
"站在路中间。当有人来和你说话时，" + pick(rng, verbs) + " 他们",
"站着不动 " + number8 + " 小时" + finaladditionalrandom,
"做后空翻" + finaladditionalrandom,
"记得刷牙" + finaladditionalrandom,
"写一本关于 " + finaltopic + " 的短篇书" + finaladditionalrandom,
"只用倒着说话",
"接下来的 " + number8 + " 小时你不能说话",
"远离光线",
"吃一袋你最喜欢的食物",
"只吃 " + finalcolorrequire + " 色的食物",
"按离你最近的按钮。你可以环顾四周找它",
"野餐，并在 " + number8 + " 小时内在" + finalllocation + "里吃掉",
"给一个 " + finalptype + finaladditionalrandom + " 发短信，问他们是否想 " + finalactivities,
"表演你的日常活动" + finaladditionalrandom,
"在接下来的 " + number8 + " 小时内不要上厕所",
"在外面待 " + number2 + " 秒"
];
let finaltask3 = pick(rng, task3);

if (finaltask0 === "" && finalstarter === "") finaltask3 = capFirst(finaltask3);
if (finaltask0 === "" && finalstarter !== "") finalstarter = capFirst(finalstarter);

const follow2up = [
" 他们的性别无关紧要。",
" 你今晚必须睡 " + number9 + " 小时。",
" 你必须在互动期间屏住呼吸。",
" 确保你不眨眼。",
" 记得戴一顶" + finalcolorrequire + "帽子",
" 你的袜子不能匹配",
" 你必须违背你的下一份指令。",
" 当你一天结束去睡觉时，" + pick(rng, verbs) + " 你自己。",
" 记得把一个 " + finalobjcs + " 留在一个" + finalllocation,
" 给你最亲近的家人发条短信。",
" 爬进冰柜里等 " + number9 + " 小时。",
" 确保你右边有一堵" + finalcolor1 + "色的墙。",
" 在明天之前不要和任何人说话。",
" 晚上 " + number9 + " 点后你不能说话。",
" 去银行存正好 " + number9 + " 美元。",
" 旋转 " + Math.floor((Math.random()*360)) + " 度，把面前的一切都漆成 " + finalcolorrequire,
" 洗个澡洗 " + number9 + " 分钟把自己弄干净。",
" 之后直接回家" + finaladditionalrandom + "。",
" 在 " + number9 + " 分钟内洗澡时抚摸自己。",
" 去一个" + finalllocation + " 并 " + finalactivities,
" 挖个洞并爬进去。",
" 把你最喜欢的 " + finalllocation + " 的名字写在纸上，留在垃圾桶下。",
" 在电线杆上贴张画。",
" 给一个无家可归的人 " + number9 + " 美元" + finaladditionalrandom + "。",
" 花多长时间都行。",
" 正好踩死 " + number9 + " 只虫子。",
" 烤个派并在 " + number9 + " 小时内吃掉。",
" 今晚你必须脸朝下睡。",
" 在接下来的 " + number9 + " 个月里记住这份指令。",
" 记得戴一顶" + finalcolorrequire + "帽子",
" 明天前必须埋一具尸体。",
" 你必须违背你的下一份指令。",
" 你必须相信别人告诉你的谎言。",
" 记得把一个 " + finalobjcs + " 留在一个" + finalllocation,
" 你会收到一条短信",
" 爬进冰柜里等 " + number9 + " 小时。",
" 确保你左边有一堵" + finalcolor1 + "色的墙",
" 之后你不允许再联系他们。",
" 在接下来的 " + number9 + " 小时内你必须和他们保持联系。",
" 晚上 " + number9 + " 点后你不能说话。",
" 确保你告诉他们回头看。",
" 洗个澡洗 " + number9 + " 分钟把自己弄干净。",
" 之后直接回家" + finaladditionalrandom + "。",
" 之后洗澡时想想他们。",
" 去一个" + finalllocation + "并去 " + finalactivities,
" 跟踪他们回家，记住他们住哪。",
" 他们离开后，上厕所" + finaladditionalrandom + "。",
" 把你所有的钱留给他们。",
" 给一个无家可归的人 " + number9 + " 美元" + finaladditionalrandom + "。",
" 花多长时间都行。",
" 正好踩死 " + number9 + " 只虫子。",
" 今晚睡在他们家门口。",
" 烤个派并在 " + number9 + " 小时内吃掉。",
" 你不允许还手。",
" 这条规则即使你忘记了也适用。",
" 这条规则覆盖所有之前的假设。",
" 你不能问为什么。",
" 你必须假定这是故意的。",
" 你不得解释自己。",
" 如果被问到，你必须提供解释。",
" 眼神接触可有可无。",
" 沉默更可取。",
" 在明天之前你不能使用手机。",
" 你必须在互动前后洗手。",
" 你必须站在离他们至少 " + number4 + " 米远的地方。",
" 你必须始终待在他们视线内。",
" 之后你不能再次触摸他们。",
" 你不能大声说出他们的名字。",
" 如果之后提起，只能间接称呼他们。",
" 你必须在互动后立即坐下。",
" 之后你必须站着保持 " + number9 + " 分钟。",
" 你必须用和来时不同的路线离开该区域。",
" 你不能原路返回。",
" 在接下来的 " + number9 + " 小时内你要避开镜子。",
" 睡觉前你必须照镜子。",
" 之后你必须喝一整杯水。",
" 在接下来的 " + number9 + " 小时内你不能吃任何东西。",
" 睡觉前你必须吃点简单的食物。",
" 一回家你就必须换衣服。",
" 回家前你不能脱鞋。",
" 今晚你必须开着灯。",
" 睡觉前你必须关掉所有的灯。",
" 午夜前你必须锁门。",
" 你必须留一扇窗户微开。",
" 你必须检查所有的门是否都关好。",
" 你不能检查门是否关好。",
" 你必须在晚上 " + number9 + " 点前上床。",
" 你必须一直醒着直到早上 " + number9 + " 点。",
" 你必须写下这件事结束的时间。",
" 你必须忘记这件事结束的时间。",
" 你不能和任何人讨论这件事。",
" 如果被问到，你必须如实回答。",
" 今天剩下的时间里你要避开公共场所。",
" 你必须在公共场所待到天黑。",
" 今天剩下的时间里你必须随身携带一个 " + finalobjcs + "。",
" 回家前你必须处理掉那个 " + finalobjcs + "。",
" 离开时你不能回头看。",
" 你必须数步数直到到达目的地。",
" 如果被打断，你必须停止计数。",
" 你必须安静地坐 " + number9 + " 分钟。",
" 在你独自一人之前不能闭眼。",
" 今晚你必须仰睡。",
" 你不能在你平时的地方睡觉。",
" 你必须再看一次时间。",
" 你不能再看时间。",
" 你必须不用闹钟醒来。",
" 你必须设个闹钟然后无视它。",
" 不要承认任何不适。",
" 不适表明有进展。",
" 此规则在 " + number9 + " 分钟后失效。",
" 此规则无限期有效。",
" 你会知道这个条件何时结束。",
" 结果无关紧要。",
" 你不会被告知这个条件何时结束。",
" 你只能在完成后哭。"
]
const finalfollowup2 = (followupChanceB === 2) ? pick(rng, follow2up) : "";
finalscript = finaltask0 + finalstarter + finaltask3 + "." + finalfollowup2;
}
return fixIndefiniteArticles(
normalizePunctuation(finalscript)
);
}
function fixIndefiniteArticles(text) {
if (!text) return text;
//should cover like every case.
text = text
.replace(/\b1\s+times\b/g, "once")
.replace(/\b2\s+times\b/g, "twice");
return text.replace(
/\b(a)\s+([A-Za-z][A-Za-z\-]*)/g,
(match, article, word) => {
const w = word.toLowerCase();
const hardVowelSound = [
"uni", "use", "user", "ufo", "euro", "one", "once", "ubiq"
];
for (const ex of hardVowelSound) {
if (w.startsWith(ex)) return match;
}
if (
w.startsWith("honest") ||
w.startsWith("hour") ||
w.startsWith("heir")
) {
return "an " + word;
}
if (/^[AEFHILMNORSX]/.test(word))
return "an " + word;
if (/^[aeiou]/.test(w))
return "an " + word;
return match;
}
);
}
let __audioUnlocked = false;
const BEEP = new Howl({
src: ["beep.mp3"],
volume: 0.25,
preload: true,
});
const BEEPSTART = new Howl({
src: ["beepstart.mp3"],
volume: 0.35,
preload: true,
});
let _lastBeepMs = 0;
function playBeep(minGapMs = 70) {
if (!__audioUnlocked) return;
const now = performance.now();
if (now - _lastBeepMs < minGapMs) return;
_lastBeepMs = now;
BEEP.stop();
BEEP.play();
}
function primeHowler() {
try {
const id = BEEP.play();
BEEP.volume(0, id);
BEEP.stop(id);
BEEP.volume(0.25);
const id2 = BEEPSTART.play();
BEEPSTART.volume(0, id2);
BEEPSTART.stop(id2);
BEEPSTART.volume(0.35);
} catch {}
}
async function unlockHowlerFromGesture() {
try {
if (window.Howler?.ctx?.state === "suspended") {
await Howler.ctx.resume();
}
__audioUnlocked = (window.Howler?.ctx?.state === "running");
if (__audioUnlocked) primeHowler();
} catch {
__audioUnlocked = false;
}
return __audioUnlocked;
}
function revealTextScramble(el, fromText, finalText, {
fps = 16,
scrambleChars = "0123456789!█▒░ABCDEF",
blockChar = "█",
revealSpeed = 0.045,
blockChance = 0.35,
beepChancePerFrame = 0.540,
minBeepGapMs = 70
} = {}) {
if (el.__revealTimer) {
clearInterval(el.__revealTimer);
el.__revealTimer = null;
}
const len = Math.max(fromText.length, finalText.length);
let progress = 0;
function randomChar() {
return Math.random() < blockChance
? blockChar
: scrambleChars[Math.floor(Math.random() * scrambleChars.length)];
}
el.__revealTimer = setInterval(() => {
progress += revealSpeed * len;
let out = "";
for (let i = 0; i < len; i++) {
const targetChar = finalText[i] ?? "";
const fromChar = fromText[i] ?? "";
if (i < progress) {
  out += targetChar;
} else {
  if (targetChar === " " || fromChar === " ") out += " ";
  else out += randomChar();
}
}
el.textContent = out;

if (progress < len && __audioUnlocked) {
if (Math.random() < beepChancePerFrame) {
  playBeep(minBeepGapMs);
}
}
if (progress >= len) {
el.textContent = finalText;
clearInterval(el.__revealTimer);
el.__revealTimer = null;
}
}, 1000 / fps);
}

function waitForClick(el) {
return new Promise(resolve => {
const handler = async () => {
await unlockHowlerFromGesture();

if (__audioUnlocked) {
  BEEPSTART.stop();
  BEEPSTART.play();
}

el.removeEventListener("click", handler);
resolve();
};
el.addEventListener("click", handler);
});
}
async function main() {
const prescriptEl = document.getElementById("prescript");
if (!prescriptEl) return;
const CLICK_TEXT = "- Click to Receive -";
const userId = getOrCreateUserId();
const today = isoDayLocal();
const lastDay = localStorage.getItem("last_day");
let script = localStorage.getItem("prescript") || "";
const alreadyRevealedToday = (today === lastDay && script);
if (alreadyRevealedToday) {
prescriptEl.classList.remove("idle");
prescriptEl.textContent = script;
return;
}
prescriptEl.textContent = CLICK_TEXT;
prescriptEl.classList.add("idle");
await waitForClick(prescriptEl);
const rng = makeDailyRng(userId);
script = generatePrescript(rng);
localStorage.setItem("prescript", script);
localStorage.setItem("last_day", today);
prescriptEl.classList.remove("idle");
revealTextScramble(prescriptEl, CLICK_TEXT, script, {
revealSpeed: 0.04,
blockChance: 0.4,
beepChancePerFrame: 0.35,
minBeepGapMs: 70
});
}
main();
})();
